### ISSUE TITLE
Any way to easily name the socket files?

### ISSUE THREAD

**Issue by andyjeffries** [ruby/debug#1016]
**Your proposal**
For our project we use a web process and a worker process (multiple of each in production, but as I'm in this repo, obviously only thinking development). With the current mechanism (as I understand it), each gets a socket created that is named after the pid of the running process, with no context of what process type it is and therefore in VS Code when it lists the sockets to connect to a) the most detailed part doesn't fit widthwise and is trimmed, and b) it then adds another step to go and look up the PID of the process to connect to. It would be nice if there was a way of naming the socket files and/or choosing their path so that users can recognise them more easily in VS Code.

**Additional context**
I tried running:

```
RUBY_DEBUG_OPEN=true RUBY_DEBUG_SOCK_PATH=./tmp/sockets/fc-worker-dbg.sock bundle exec sidekiq -t 10 -C config/sidekiq.yml
```

But the command that VS Code's extension uses to list the sockets doesn't find them:

```
rdbg --util=list-socks
```

Maybe this is currently achievable and I'm just missing how to configure it, but if that's the case I'm happy to raise a PR for the docs once someone educates me :-)

**Comment by ko1** [comment]
Could you add same envval `RUBY_DEBUG_SOCK_PATH` for VSCode?

**Comment by andyjeffries** [comment]
I don't think this is necessary with #1017, it solves the same problem (being able to name the socket in some way recognisably). Combined with https://github.com/ruby/vscode-rdbg/pull/349 this is a fuller worker solution for us.

I'm happy for this #1016 to be closed.
