### ISSUE TITLE
Setting the irb_console configuration true has no effect

### ISSUE THREAD

**Issue by joe-sharp** [ruby/debug#1062]
**Your environment**

* `ruby -v`: 3.2.2 (also tested at 3.1.4p223, 3.0.6p216, and even 2.7.8p225)
* `rdbg -v`: 1.9.1
* `irb -v`: 1.11.1

**Describe the bug**
Setting the irb_console to true has no effect, and the environment variable RUBY_DEBUG_IRB_CONSOLE must be used to have rdbg and its breakpoint always start the user out with the irb:rdbg console.

**To Reproduce**

**Expected behavior**
I didn't expect that setting the configuration inside the REPL would take immediate effect so I created a `~/.rdbgrc` file with a single line:
```rb
config set irb_console true
```
I would expect that hitting a debugger breakpoint or using the rdbg command would invoke the irb:rdgb console. To achieve the behavior I expect, I set the RUBY_DEBUG_IRB_CONSOLE env var to true in my `~/.zshenv` instead.

**Additional context**
I do see the following message print after creating the `~/.rdbgrc` file:
```rb
(rdbg:/Users/joesharp/.rdbgrc) config set irb_console true
irb_console = true                 # UI: Use IRB as the console (default: false)
```
Checking `config irb_console` shows the same line.

**Comment by st0012** [comment]
Thanks for reporting! I opened #1057 to address this.
