### ISSUE TITLE
Could not find valid gem

### ISSUE THREAD

**Issue by SailingDreams** [ruby/debug#1087]
**Your environment**
Windows 10

* `ruby -v`: ruby 2.4.4p296 (2018-03-28 revision 63013) [i386-mingw32]
* `rdbg -v`: >rdbg -v
'rdbg' is not recognized as an internal or external command,
operable program or batch file.

**Describe the bug**
Running "gem install debug" returns the following error

**To Reproduce**
C:>gem install debug
ERROR: Could not find a valid gem 'debug' (>= 0) in any repositor'

**Expected behavior**
The debug install occurs.

**Additional context**
C:\>gem install debug
ERROR:  Could not find a valid gem 'debug' (>= 0) in any repository

C:\>gem --version
2.6.14.1

C:\>gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.2)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.4)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.7)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)

**Comment by hsbt** [comment]
Because `debug` gem needs to Ruby 2.7 or later.

https://github.com/ruby/debug/blob/master/debug.gemspec#L13

You should upgrade your Ruby version.
