### ISSUE TITLE
Cut a new release for the Rails stdin bug

### ISSUE THREAD

**Issue by freesteph** [ruby/debug#1091]
Hello,

There is a bug with Ruby 3.3 which has been solved in the master branch (e4e6545ebdb67e04997068c37f9394f2c0644586). Could you please cut a new minor release to get the change? Pointing at the git master branch from Bundler is a bit of a hassle in a lot of our projects.

Thank you very much.

**Comment by freesteph** [comment]
🙏

**Comment by ko1** [comment]
👍
