### ISSUE TITLE
Autocomplete not in parity with irb?

### ISSUE THREAD

**Issue by brandoncc** [ruby/debug#1112]
**Your environment**

* `ruby -v`: ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
* `rdbg -v`: rdbg 1.9.2

**Describe the bug**

- If I open `irb` and type "put", I get completion options for "putc" and "puts".
- If I run `bin/rails console`, I get the same.
- If, within the rails console, I run `binding.debugger`, typing "p" gets me autocomplete options only for "p" and "pp".

Is this intended behavior, or is there configuration that would fix this? For comparison, I get the same result in pry as I do in irb ("putc"/"puts").

**Comment by tompng** [comment]
I think this will solve it https://github.com/ruby/debug?tab=readme-ov-file#using-irb-as-the-debug-console
```md
If you want to make IRB the default console for all sessions, configure the `irb_console` setting by either:

* Setting the `RUBY_DEBUG_IRB_CONSOLE=true` environment variable
* Or adding `config set irb_console 1` to your `~/.rdbgrc`
```

**Comment by brandoncc** [comment]
That fixed it, thank you.
