### ISSUE TITLE
Arrow keys are not working when debugging

### ISSUE THREAD

**Issue by BenKanouse** [ruby/debug#1127]
**Your environment**

* `ruby -v`:  `ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-darwin23]`
* `rdbg -v`:  `rdbg 1.10.0`

**Describe the bug**
When I debug a ruby script I am not able to use the arrow keys.

**To Reproduce**

gemfile
``` gemfile
source 'https://rubygems.org'

ruby '3.3.4'

gem 'debug'
```

issue.rb
``` ruby
require 'debug'

debugger
puts 'something'
```

running the script and hitting the up arrow:
```
➜  ruby issue.rb
[1, 4] in issue.rb
     1| require 'debug'
     2|
=>   3| debugger
     4| puts 'something'
=>#0	<main> at issue.rb:3
(rdbg) ^[[A
```

**Expected behavior**
I expect the up arrow to go throw history and the left array to be able to move backwards on the line.

**Additional context**
Thank you so much for this gem!

I suspect something is wrong with my setup/OS that is causing this issue, but I am not sure how to track it down at this point and would appreciate any feedback.

I am able to use the arrow keys if I swap `debug` gem out for the `pry` gem, and the arrow keys work in `irb`.

**Comment by st0012** [comment]
I can't reproduce this issue. Can you try the following approaches:
- Run `bundle exec ruby issue.rb` to make sure it picks up `debug` `v1.10.0` instead of the version shipped with Ruby 3.3.4?
- Check if the `reline` version in `Gemfile.lock` is the latest release

**Comment by BenKanouse** [comment]
Thank you for the help!

I am still seeing the issue with `bundle exec ruby issue.rb`

![Screenshot 2024-12-19 at 3 16 59 PM](https://github.com/user-attachments/assets/378bf3f6-f554-404f-af77-0dfa84bb019d)

The gemfile is showing `reline` at `0.6.0`.

<details>
<summary> Full Gemfile.lock </summary>
```
GEM
  remote: https://rubygems.org/
  specs:
    date (3.4.1)
    debug (1.10.0)
      irb (~> 1.10)
      reline (>= 0.3.8)
    io-console (0.8.0)
    irb (1.14.3)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    psych (5.2.2)
      date
      stringio
    rdoc (6.10.0)
      psych (>= 4.0.0)
    reline (0.6.0)
      io-console (~> 0.5)
    stringio (3.1.2)

PLATFORMS
  ruby
  x86_64-darwin-23

DEPENDENCIES
  debug

RUBY VERSION
   ruby 3.3.4p94

BUNDLED WITH
   2.5.14
 ```
 </details>

**Comment by BenKanouse** [comment]
I have some new information!

It works fine if I `sudo ruby issue.rb`. So I must have installed something with the the wrong privileges.

I think this issue could be closed since it sounds like it is likely not an issue with the gem. I can continue to update the issue with more information once I find my permissions issue.

**Comment by BenKanouse** [comment]
For anyone else who encounters this problem, I was able to resolve it by removing the following line from my ~/.zshrc file:

```
export RUBY_DEBUG_NO_RELINE=1
```

After removing this line, the arrow keys started working as expected during debugging. Thanks to the maintainers for their hard work on this gem!
