### ISSUE TITLE
Some commands shouldn't be automatically repeated

### ISSUE THREAD

**Issue by st0012** [ruby/debug#113]
The debugger repeats the previous command when the user gives an empty input. This is neat for flow or frame control commands. But for commands (especially breakpoint commands) it's not necessary. 

So here's the list of commands I think we should exclude:
- all the breakpoint commands - doesn't make sense
- ~`eval`~
- `irb` - it's annoying to accidentally enter the `irb` session by hitting `<enter>`

**Comment by st0012** [comment]
@ko1 what's your thought on this?

**Comment by ko1** [comment]
They make sense.

I think `eval` can allow because some expressions can have side-effect (and if it doesn't have side-effect, it is also no problem):

on gdb:

```
(gdb) p 1
$1 = 1
(gdb)
$2 = 1
(gdb)
$3 = 1
```

**Comment by st0012** [comment]
@ko1 I'll keep eval then 👍
