### ISSUE TITLE
Testing with remote mode is not stable

### ISSUE THREAD

**Issue by st0012** [ruby/debug#118]
When testing locally with **Ruby 3.1.0-dev**, I sometimes get errors like this:
```
Error: test_break_with_namespaced_class_method_stops_at_correct_place(DEBUGGER__::BreakAtMethodsTest): Errno::EMFILE: Too many open files - fork failed
/Users/st0012/projects/debug/test/support/utils.rb:77:in `spawn'
/Users/st0012/projects/debug/test/support/utils.rb:77:in `block in new_child_process'
```

Or timeout error:

```
Failure: test_backtrace_prints_the_return_value(DEBUGGER__::BasicBacktraceTest):
  TIMEOUT ERROR (10 sec)
  [DEBUG SESSION LOG]
  > [1, 10] in /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210701-59574-vo4b86.rb
  > =>    1| class Foo
  >       2|   def first_call
  >       3|     second_call(20)
  >       4|   end
  >       5|
  >       6|   def second_call(num)
  >       7|     third_call_with_block do |ten|
  >       8|       num + ten
  >       9|     end
  >      10|   end
  > =>#0        <main> at /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210701-59574-vo4b86.rb:1
  > b 4
  >
  > (rdb) b 4
  .
  <false> is not true.
```

The master build also [fails for timeout error](https://github.com/ruby/debug/runs/2959987864?check_suite_focus=true). I can't rerun it but it looks like a random failure too.

**Comment by st0012** [comment]
@ono-max can you take a look? thanks

**Comment by ono-max** [comment]
I think this is not issue.I saw kind of this error before merging remote test.

Since we started testing on remote, the number of tests increased by 3 times.That's why probability of random failure also increased.

**Comment by ono-max** [comment]
Hmm... I can't reproduce the `Errno::EMFILE:`. When I look into it, it may be able to be solved this problem by configuring your local environment.

**Comment by st0012** [comment]
This issue happens a lot on Ruby `3.1.0-dev`, have you tested against it?

> Since we started testing on remote, the number of tests increased by 3 times.That's why probability of random failure also increased.

Even with remote tests, we only have < 500 assertions. It's not acceptable to just say "oh it fails sometime". 
Random failures make our tests unreliable and increase the chance to let real issues slip in. It also increased the maintainers' work because now the CI needs to reran very often.

**Comment by st0012** [comment]
In the recent 8 builds, 4 of them failed, including `master`'s. The 50% chance of failure is too high to accept.
<img width="80%" alt="截圖 2021-07-02 上午9 29 55" src="https://user-images.githubusercontent.com/5079556/124207418-113f6f00-db18-11eb-95ec-78efd671dd9e.png">

**Comment by ono-max** [comment]
> This issue happens a lot on Ruby 3.1.0-dev, have you tested against it?

Sorry, I missed the version. I'll check it again.

**Comment by ono-max** [comment]
I fixed `Errno::EMFILE: Too many open files - fork failed`, so I'll continue to investigate how to fix `TimeoutError`.

**Comment by st0012** [comment]
@ono-max that sounds great, thank you 👍

**Comment by ono-max** [comment]
@st0012 
I think we can close this issue because TimeoutError was fixed in https://github.com/ruby/debug/pull/131.
Do you agree?

**Comment by st0012** [comment]
sure, thanks for al the fixes 😄
