### ISSUE TITLE
Proposal on backtrace (bt command) format

### ISSUE THREAD

**Issue by st0012** [ruby/debug#13]
I really like the useful information added to the backtrace (like arguments, block parameters...etc.). It's something I've been looking for for a long time.

And because I saw @ko1 asking for feedback on the backtrace format [in his tweet](https://twitter.com/_ko1/status/1391682538020630529), I think I can provide my 2 cents here.

### Example

This is the example script I'll use to generate the output for my proposal:

```ruby
class Foo
  def first_call
    second_call(20)
  end

  def second_call(num)
    third_call_with_block do |ten|
      forth_call(num, ten)
    end
  end

  def third_call_with_block(&block)
    @ivar1 = 10; @ivar2 = 20

    yield(10)
  end

  def forth_call(num1, num2)
    require "debug" # <= breakpoint
  end
end

Foo.new.first_call
```

And this is the output it generates for the `bt` command.

```
=>#0    Foo#forth_call(num1=20, num2=10) at foo.rb:21 #=> true
  #1    block{|ten=10|} in second_call at foo.rb:8
  #2    Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>) at foo.rb:15
  #3    Foo#second_call(num=20) at foo.rb:7
  #4    first_call at foo.rb:3
  #5    <main> at foo.rb:24
```

### Introduction of Components

I know most people reading this issue are already contributor to it and are familiar with the information contained in the backtrace. But I still want to do a short introduction to those who're not that familiar with it yet.

#### Trace Type - Call With Arguments

```
=>#0    Foo#forth_call(num1=20, num2=10) at foo.rb:21 #=> true
```

- `=>#0` - prompt + frame index
- `Foo#forth_call` - class + callee
- `(num1=20, num2=10)` - args
- `at foo.rb:21` - location
- `#=> true` - return value

#### Trace Type - Block Evaluation

```
  #1    block{|ten=10|} in second_call at foo.rb:8
```

- `#1` - prompt + frame index
- `block{|ten=10|} in second_call` - block label & parameters
- `at foo.rb:8` - location

## So, the Format

Ok, let's back to the backtrace:

```
=>#0    Foo#forth_call(num1=20, num2=10) at foo.rb:21 #=> true
  #1    block{|ten=10|} in second_call at foo.rb:8
  #2    Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>) at foo.rb:15
  #3    Foo#second_call(num=20) at foo.rb:7
  #4    first_call at foo.rb:3
  #5    <main> at foo.rb:24
```

To me, the main drawback of the current format is: it's hard to read the full trace at once.

This is the normal Ruby backtrace for the same script:

```
foo.rb:8:in `block in second_call'
foo.rb:15:in `third_call_with_block'
foo.rb:7:in `second_call'
foo.rb:3:in `first_call'
foo.rb:24:in `<main>'
```

As a Rubyist, I'm used to having the call site upfront so I can read them directly, from top to bottom.

But in the new format, call site is placed after information like class, callee, and args. So it'll appear in the different column in different lines. 

This means I need to perform a search on each line:

- Searching for the pattern of a trace.
  - Sometime this doesn't work that well. For example, the `#2` frame has 2 traces. One of the Proc object and one for the actual call location.
- Or searching for the `at` keyword.

To improve this, I want to propose the following options as a start:

### Option 1 - Don't Change Information Order. Just Replace `at` With Different Symbols

We're better at distinguishing symbols then letters in a pile of texts. So if we don't want to change the order of information, replacing `at` with a symbol should help locating the call site too. Some examples:

#### `|`

```
=>#0    Foo#forth_call(num1=20, num2=10) | foo.rb:21 #=> true
  #1    block{|ten=10|} in second_call | foo.rb:8
  #2    Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>) | foo.rb:15
  #3    Foo#second_call(num=20) | foo.rb:7
  #4    first_call | foo.rb:3
  #5    <main> | foo.rb:24
```

#### `@`

```
=>#0    Foo#forth_call(num1=20, num2=10) @ foo.rb:21 #=> true
  #1    block{|ten=10|} in second_call @ foo.rb:8
  #2    Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>) @ foo.rb:15
  #3    Foo#second_call(num=20) @ foo.rb:7
  #4    first_call @ foo.rb:3
  #5    <main> @ foo.rb:24
```

#### `#`

```
=>#0    Foo#forth_call(num1=20, num2=10) # foo.rb:21 #=> true
  #1    block{|ten=10|} in second_call # foo.rb:8
  #2    Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>) # foo.rb:15
  #3    Foo#second_call(num=20) # foo.rb:7
  #4    first_call # foo.rb:3
  #5    <main> # foo.rb:24
```

#### With Separator (Not Aligned)

```
=>#0    foo.rb:21 | Foo#forth_call(num1=20, num2=10) #=> true
  #1    foo.rb:8 | block{|ten=10|} in second_call
  #2    foo.rb:15 | Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>)
  #3    foo.rb:7 | Foo#second_call(num=20)
  #4    foo.rb:3 | first_call
  #5    foo.rb:24 | <main>
```

#### With Separator (Aligned)

```
=>#0    foo.rb:21 | Foo#forth_call(num1=20, num2=10) #=> true
  #1    foo.rb:8  | block{|ten=10|} in second_call
  #2    foo.rb:15 | Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>)
  #3    foo.rb:7  | Foo#second_call(num=20)
  #4    foo.rb:3  | first_call
  #5    foo.rb:24 | <main>
```

This looks good but not really practical because the length of call site also can vary a lot, like

```
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/rubygems_integration.rb:390:in `block in replace_bin_path'
from /Users/st0012/.rbenv/versions/3.0.1/bin/pry:23:in `<top (required)>'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
from /Users/st0012/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
from /Users/st0012/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'
```

### 2 Lines

With the amount of information to display, I think having 2 lines for each trace is a reasonable option too.

#### With Separator

```
=>#0    foo.rb:21 
          Foo#forth_call(num1=20, num2=10) #=> true
  #1    foo.rb:8
          block{|ten=10|} in second_call
  #2    foo.rb:15
          Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>)
  #3    foo.rb:7 
          Foo#second_call(num=20)
  #4    foo.rb:3 
          first_call
  #5    foo.rb:24 
          <main>
```

#### `With a 2nd-line indicator (my preference)`

I find having an indicator helps me read the lines better. Among all the options, this is my favorite.

```
=>#0    foo.rb:21 
          | Foo#forth_call(num1=20, num2=10) #=> true
  #1    foo.rb:8
          | block{|ten=10|} in second_call
  #2    foo.rb:15 
          | Foo#third_call_with_block(block=#<Proc:0x00007fc645174d10 foo.rb:7>)
  #3    foo.rb:7 
          | Foo#second_call(num=20)
  #4    foo.rb:3 
          | first_call
  #5    foo.rb:24 
          | <main>
```

### Other Options

This issue is just to continue the discussion with some of my ideas. And I believe there are many better options out there. So if you also have any thoughts on this, please leave a comment too :smile:

---

## Update

@ko1 and I have colorized the backtrace and it now looks a lot better 🙂 

<img width="80%" alt="截圖 2021-05-26 上午11 21 56" src="https://user-images.githubusercontent.com/5079556/119597937-98603f80-be14-11eb-9c3b-d4592b4f1733.png">
<img width="80%" alt="截圖 2021-05-26 上午11 24 16" src="https://user-images.githubusercontent.com/5079556/119598118-ebd28d80-be14-11eb-9024-ce8c7b892687.png">

---

**Comment by mcansky** [comment]
great summary, thanks for the efforts !

my personal preference goes to "With Separator (Aligned)".

Although I can see the appeal of two lines I find it less readable with the many line breaks. In my opinion single lines make it easier to spot differences in a pattern (path change for one). Having additional line breaks add visual breaks that already break any pattern.

**Comment by st0012** [comment]
@mcansky Thanks for the comment! 

I agree that it'd be the best to have no line break at all. But I also worry that the call site + additional info would make the line too long for most people. If that happens, they'd still have 2 lines on their screens. 

I'll try several scenarios to see if the line length would cause any readability issue and post the result here 🙂

**Comment by st0012** [comment]
@mcansky  I've implemented `With Separator (Aligned)` and here are what I found:

1. It looks really good in a `wide (character-length wise)` terminal.
<img width="80%" alt="aligned trace in wide screen" src="https://user-images.githubusercontent.com/5079556/119082293-59a34180-ba30-11eb-9eda-720b6ae37812.png">

2. It looks terrible in a `narrow` terminal.
<img width="80%" alt="aligned trace in narrow screen" src="https://user-images.githubusercontent.com/5079556/119082385-89524980-ba30-11eb-841d-c48b3d2944b8.png">

If the screen is not wide enough (character-length wise), the lines would still break and make it very hard to spot the patterns. And because the point of line break is not controllable, it'll looks worse than the `2 lines` option imo.

Because the average length of trace is above 200 characters, I think many users will face the 2nd condition and have a hard time reading the backtrace. So I don't think that's a good default format (but can be an configurable option).

And as a comparison, this is the result of `2 lines` approach:

1. `wide` terminal
<img width="80%" alt="2-lines trace in wide screen" src="https://user-images.githubusercontent.com/5079556/119083165-04682f80-ba32-11eb-9984-b612fef0bb34.png">

2. `narrow` terminal
<img width="80%" alt="2-lines trace in narrow screen" src="https://user-images.githubusercontent.com/5079556/119083186-0e8a2e00-ba32-11eb-92d0-d6f2b44482e4.png">

Finally, this is the current output:

<img width="80%" alt="default" src="https://user-images.githubusercontent.com/5079556/119083601-d800e300-ba32-11eb-8a1d-e708b1c58db2.png">


@ko1 wdyt?

**Comment by ko1** [comment]
They should be output in HTML in browser.

**Comment by st0012** [comment]
@ko1 I don't think I get it. is backtrace suppose to be read inside a browser but not terminal and I'm doing it wrong? or you're talking about the eventual goal, so we just leave the current format as it is? 🤔

**Comment by ko1** [comment]
Sorry it was joking that they are so many information and they should be folded in browser.
And it is not complete joke, introduce browser view is another advanced topic. terminal + browser view for example.

**Comment by st0012** [comment]
yes I totally agree. ideally we should have a dedicated window to display additional information (like `info`).
I think we can improve the readability of backtrace (or other information) in 3 major stages:

1. format tweaking (like this PR tries to do)
2. colorize text
3. split view, which can be done according to the user's preference. some examples:
    - browser view
    - editor's window/pane
    - tmux's window/pane

I'm not sure how Ruby core team's roadmap for this looks like. but I think we should be able to achieve the 2nd stage before  its official release? (assume it's the same day as Ruby 3.1?)

**Comment by mcansky** [comment]
@st0012 I agree, it's difficult to pick a solution that matches all needs. So maybe pick one you get the most approval for and we will see if it needs revisiting later ?

Nowadays, in my case and with many of my teams at least, stacktraces are viewed within appsignal/sentry/newrelic/honeybadger/.... and very rarely through the terminal except when writing and debugging code locally. So I would be ok with any of the suggestion you make really even though I have a preference.

Just wondering though : any possibility to have the concept of "formatter" we could configure ?

**Comment by ko1** [comment]
gdb example

![image](https://user-images.githubusercontent.com/9558/119157723-70798080-ba90-11eb-942c-7ce92ad69873.png)

with narrow window:

![image](https://user-images.githubusercontent.com/9558/119157851-8e46e580-ba90-11eb-8e4d-ea308e6c8b4c.png)

**Comment by ko1** [comment]
coloring and pretty line breaks helps?

**Comment by ko1** [comment]
can you find other debuggers output?

**Comment by ko1** [comment]
> Just wondering though : any possibility to have the concept of "formatter" we could configure ?

This is one idea, but we should provide recommended format by default.

**Comment by st0012** [comment]
> can you find other debuggers output?

I don't write other languages these days. I did write Go before but the debugger was integrated with the Jetbrain IDE's GUI. So it was like clickable traces instead of a terminal output.

> gdb example

I think colorizing makes a huge difference. I'm happy to live with the current format if we can colorize the backtrace soon enough. However, we should still compare different formatting options after we've colorized different components to find room for improvements.

**Comment by mcansky** [comment]
> > Just wondering though : any possibility to have the concept of "formatter" we could configure ?
> 
> This is one idea, but we should provide recommended format by default.

definitely

**Comment by st0012** [comment]
Just to give a quick update on this: @ko1 and I have colorized the backtrace (and frame source code), which makes the output easily understandable now:

<img width="80%" alt="截圖 2021-05-27 下午12 46 54" src="https://user-images.githubusercontent.com/5079556/119767559-9f0cb680-bee9-11eb-8376-b23568a989b0.png">

So I don't think the re-formatting is required anymore and will close the issue.

Note: the color/font styling might still change in the future.

**Comment by ko1** [comment]
Now we have `width` information so we can improve more.

**Comment by st0012** [comment]
@ko1 do you mean something like presenting line break format on a narrow screen?

**Comment by ko1** [comment]
Sorry I missed your comment. Yes. Use 2 lines on narrow screen for example.
