### ISSUE TITLE
Inconsistent binding in CatchBreakpoint with primitive exceptions

### ISSUE THREAD

**Issue by st0012** [ruby/debug#139]
When stopped at a breakpoint, evaluating `binding` should reflect the current scope's binding.

<img width="80%" alt="截圖 2021-07-07 下午12 45 54" src="https://user-images.githubusercontent.com/5079556/124701522-50f3c580-df21-11eb-9865-eab22383986a.png">

But it's not the case when stopped at `CatchBreakpoint` with some primitive exceptions like `ZeroDivisionError`.

<img width="80%" alt="截圖 2021-07-07 下午12 45 38" src="https://user-images.githubusercontent.com/5079556/124701526-53eeb600-df21-11eb-9f3a-5bb5f0258313.png">

It's because those exceptions are raised in C source code, which's frame doesn't have a binding. So the debugger falls back to its own frame.

https://github.com/ruby/debug/blob/c15a460266dce5e2aebd40041176be0c5a31d5e6/lib/debug/thread_client.rb#L338-L345

I'm not sure if this edge case counts as a bug. But it'd be nice if the debugger can fall back to the nearest Ruby-level frame (with binding) in such cases.

**Comment by ko1** [comment]
I think `self` should be C method's `self`, so select nearest Ruby binding will introduce confusing.

On the other hand, visible for local variables seems bad. I'll fix it.

```
(rdbg) p binding.local_variables
=> [:frame_self, :src]
```

2 variables `[:frame_self, :src]` are visible, but I don't have idea to hide them.

```patch
diff --git a/lib/debug/thread_client.rb b/lib/debug/thread_client.rb
index 792f966..eeac247 100644
--- a/lib/debug/thread_client.rb
+++ b/lib/debug/thread_client.rb
@@ -331,6 +331,10 @@ module DEBUGGER__
       end
     end

+    def instance_eval_for_cmethod frame_self, src
+      frame_self.instance_eval(src)
+    end
+
     def frame_eval src, re_raise: false
       begin
         @success_last_eval = false
@@ -341,7 +345,7 @@ module DEBUGGER__
                    b.eval(src, "(rdbg)/#{f}")
                  else
                    frame_self = current_frame.self
-                   frame_self.instance_eval(src)
+                   instance_eval_for_cmethod(frame_self, src)
                  end
         @success_last_eval = true
         result
```

Another idea is to prohibit evaluation on C method frame. But it is useful to access self.

**Comment by ko1** [comment]
BTW, I can't see the response of `catch` command.

![image](https://user-images.githubusercontent.com/9558/124706818-d338b580-df32-11eb-9d28-5bc35f733fd9.png)

Do you know why?

**Comment by ko1** [comment]
I got it.

```patch
diff --git a/lib/debug/session.rb b/lib/debug/session.rb
index 7df8468..b46560b 100644
--- a/lib/debug/session.rb
+++ b/lib/debug/session.rb
@@ -920,6 +920,9 @@ module DEBUGGER__
     # breakpoint management

     def add_breakpoint bp
+      # don't repeat commands that add breakpoints
+      @repl_prev_line = nil
+
       if @bps.has_key? bp.key
         unless bp.duplicable?
           @ui.puts "duplicated breakpoint: #{bp}"
@@ -928,9 +931,6 @@ module DEBUGGER__
       else
         @bps[bp.key] = bp
       end
-
-      # don't repeat commands that add breakpoints
-      @repl_prev_line = nil
     end

     def rehash_bps
```

**Comment by st0012** [comment]
@ko1 ah sorry it's my fault. thanks for catching it 👍
