### ISSUE TITLE
Allow specifying inspection mode when using the info command

### ISSUE THREAD

**Issue by st0012** [ruby/debug#140]
Current `info` command pretty inspects everything, which could be an issue when used in a Rails application. For example, a Rails controller usually has many instance variables that contain big objects. And calling inspect on them creates noise.
<img width="80%" alt="截圖 2021-07-07 下午3 27 32" src="https://user-images.githubusercontent.com/5079556/124717744-016cc400-df38-11eb-8dc2-6038a710b308.png">

(more than 2000 lines after the screenshot)

So it'd be great to provide something like `info -s` as simple mode (calling `to_s` instead of `inspect`)

**Comment by ko1** [comment]
or cut them into one line or few lines on the default?

**Comment by st0012** [comment]
I think the best solution is to expand the object with only one level:

```ruby
# given
class Foo
  def initialize(bar)
    @bar = bar
  end
end

class Bar
  def initialize
    @some_var = 123
  end
end

foo = Foo.new(Bar.new)
# expand foo but not its @bar variable
foo.special_inspect #=> #<Foo:0x00007fbf855d3a12 @bar=#<Bar:0x00007fbf855d3a80 ...>>
```

and then make our own `ColorPrinter` to utilize it.
but it looks like `PrettyPrint` library doesn't support this. do you think it's worth implementing one ourselves?

**Comment by ko1** [comment]
![image](https://user-images.githubusercontent.com/9558/124962148-3f153e00-e059-11eb-89ea-8793f550f8a8.png)

How about that? It is better than 2000 lines.

**Comment by st0012** [comment]
Yes that looks a lot better 👍

**Comment by ko1** [comment]
Another idea is to pass long string to `less` command.

**Comment by ko1** [comment]
Until support `less` pager, I introduce it.
(`less` is difficult for remote console)
