### ISSUE TITLE
Breakpoint won't fire if console last statement

### ISSUE THREAD

**Issue by adam12** [ruby/debug#16]
From the README:

```ruby
# target.rb
require 'debug/session'  # introduce the functionality
DEBUGGER__.console       # and start the debug console
```

I'd expect this to work, but it doesn't.

```
root@5614f7e87baa:/workspace# bundle exec ruby target.rb 
root@5614f7e87baa:/workspace# echo $?
0
```

Adding a statement following the `console` call will trigger the breakpoint. It can be a no-op line like `nil`.

```ruby
require 'debug/session'  # introduce the functionality
DEBUGGER__.console       # and start the debug console

nil
```

```
root@5614f7e87baa:/workspace# bundle exec ruby target.rb 
[1, 4] in target.rb
      1| require 'debug/session'  # introduce the functionality
      2| DEBUGGER__.console       # and start the debug console
      3| 
=>    4| nil
=>#0    <main> at target.rb:4

(rdbg) 
```

I'm fairly sure the breakpoint being setup here is 1 line off in this scenario, but I'm not sure how to fix it at first glance.

https://github.com/ruby/debug/blob/5b20343ec0f172d075b2f34dcd3e90eb6d0c1ea1/lib/debug/session.rb#L969

**Comment by ko1** [comment]
What should it happen?

**Comment by adam12** [comment]
I'd probably expect the debugger to start.

This usage might not be very common since the `rdbg` executable exists, but the `README` shows it as an example, so perhaps the `README` needs to be updated?

**Comment by ko1** [comment]
The doc shows `...` and I assumed it is some code.
Anyway, I understand the surprise.
Let me think more.

Maybe, if there is no code just after `console` method, it can stop some ponits...

**Comment by adam12** [comment]
> The doc shows `...` and I assumed it is some code

Oh, you're right! I didn't even see the `...`. Maybe a tweak to the README will help, at least for now.

**Comment by st0012** [comment]
@adam12 both the readme and startup commands have changed a lot, do you think this can be closed?

**Comment by adam12** [comment]
I say we close it unless it comes back up again.

**Comment by st0012** [comment]
If you use `binding.b`, it stops at the last line now

```
❯ ruby -Ilib -r debug target.rb
DEBUGGER: Session start (pid: 86155)
[1, 1] in target.rb
=>    1| binding.b
=>#0    <main> at target.rb:1
```
