### ISSUE TITLE
break command like `bp(command:)`

### ISSUE THREAD

**Issue by ko1** [ruby/debug#164]
I want to introduce same functionality of `bp(command:)`
The problem is it is hard to define the syntax because of combination of `if`.

```
break ... do <command>
# break 10 do p lvar

break ... if <expr> do <command>
# break 10 if lvar > 100 do p lvar
```

for eample?

**Comment by ko1** [comment]
ah, I'll change the syntax `if` to `if:` and introduce `do:` to recognize Ruby's expression and debug command.

**Comment by ko1** [comment]
```ruby
diff --git a/lib/debug/session.rb b/lib/debug/session.rb
index 7d08492..889f063 100644
--- a/lib/debug/session.rb
+++ b/lib/debug/session.rb
@@ -344,10 +344,12 @@ module DEBUGGER__
       #    * Set breakpoint on the method `<class>#<name>`.
       # * `b[reak] <expr>.<name>`
       #    * Set breakpoint on the method `<expr>.<name>`.
-      # * `b[reak] ... if <expr>`
+      # * `b[reak] ... if: <expr>`
       #   * break if `<expr>` is true at specified location.
-      # * `b[reak] if <expr>`
-      #   * break if `<expr>` is true at any lines.
+      # * `b[reak] ... do: <command>`
+      #   * break and run `<command>`, and continue.
+      # * `b[reak] if: <expr>`
+      #   * break if: `<expr>` is true at any lines.
       #   * Note that this feature is super slow.
       when 'b', 'break'
         if arg == nil
```

should we add an option to stop option? (run command and not continue)

**Comment by st0012** [comment]
> ```ruby
> diff --git a/lib/debug/session.rb b/lib/debug/session.rb
> index 7d08492..889f063 100644
> --- a/lib/debug/session.rb
> +++ b/lib/debug/session.rb
> @@ -344,10 +344,12 @@ module DEBUGGER__
>        #    * Set breakpoint on the method `<class>#<name>`.
>        # * `b[reak] <expr>.<name>`
>        #    * Set breakpoint on the method `<expr>.<name>`.
> -      # * `b[reak] ... if <expr>`
> +      # * `b[reak] ... if: <expr>`
>        #   * break if `<expr>` is true at specified location.
> -      # * `b[reak] if <expr>`
> -      #   * break if `<expr>` is true at any lines.
> +      # * `b[reak] ... do: <command>`
> +      #   * break and run `<command>`, and continue.
> +      # * `b[reak] if: <expr>`
> +      #   * break if: `<expr>` is true at any lines.
>        #   * Note that this feature is super slow.
>        when 'b', 'break'
>          if arg == nil
> ```
> 
> should we add an option to stop option? (run command and not continue)

In that case I think a separate command like `run` or `perform` would be better.

**Comment by ko1** [comment]
like `run target.rb:3 do p 1` ?

**Comment by ko1** [comment]
https://lldb.llvm.org/use/tutorial.html#setting-breakpoints
lldb uses `-C` and so on.

**Comment by ko1** [comment]
1f99707bb5036c8dff25685b2d26860d40e05651
