### ISSUE TITLE
Line bp with do: option doesn't stop by default

### ISSUE THREAD

**Issue by st0012** [ruby/debug#166]
I assume the line bp should still stop after the `do` option is performed? Currently it's not

<img width="80%" alt="截圖 2021-07-12 下午2 37 55" src="https://user-images.githubusercontent.com/5079556/125241985-c0512700-e31e-11eb-8cb8-06988d6496d8.png">

But it stops when performed with other options (see the additional `c` command):

<img width="80%" alt="截圖 2021-07-12 下午2 38 58" src="https://user-images.githubusercontent.com/5079556/125242132-e5459a00-e31e-11eb-88b5-8d9377d58f2d.png">

**Comment by st0012** [comment]
btw I'm adding tests for the new option.

**Comment by ko1** [comment]
Used by `-e` will cause this issue.

**Comment by st0012** [comment]
It doesn't stop with direct command call either:

<img width="662" alt="截圖 2021-07-12 下午2 51 16" src="https://user-images.githubusercontent.com/5079556/125243385-9e58a400-e320-11eb-88af-1ccc6d3f35d3.png">

**Comment by ko1** [comment]
ah, sorry.
Same as `binding.bp(command:)` it continues.

**Comment by st0012** [comment]
@ko1 I've opened #168 for this.
