### ISSUE TITLE
improve `binding.bp(command:)`

### ISSUE THREAD

**Issue by ko1** [ruby/debug#169]
Some ideas from https://github.com/ruby/debug/issues/148#issuecomment-878365619

## command passing

`binding.bp(command: 'A ;; B ;; C')` will be use frequently, so we can improve it.

* `command:` -> `do:`
  * `binding.bp do: 'A ;; B ;; C'`
  * shorter than `command:`
  * same as `break do:` command
* Accept command without keyword
  * `binding.bp('A ;; B ;; C')`
  * But it is too cryptic (bp may be already cryptic :p) 
* accept Array
  * `binding.bp do: %w(A B C)`

## nonstop control

Now `binding.bp(command: 'info', nonstop: false)` will stop after `info` command.
We can introduce shorter way.

* Different keyword
  * `binding.bp(do: ...)` for nonstop (by default)
  * `binding.bp(before: ...)` for stop, but run given command *before* stopping
  * `binding.bp(pre: ...)` for stop, but run given command as *pre*-process

I think `do:` and `pre:` seems nice.

## better method name

Now debug command is `b` or `break`. Renaming `binding.bp` to `binding.break` is one idea. And we can make an alias `binding.b`. I'm not sure we can introduce as default, but we can define it in `~/.rdbgrc.rb`.

**Comment by st0012** [comment]
I think `binding.bp('A ;; B ;; C')` is 👍 
But I don't think it's necessary to add an additional option for nonstop. Simply `binding.bp("C1 ;; C2 ;; c")` requires less key stroke and doesn't require learning additional `nonstop` concept + saves additional implementation.

**Comment by ko1** [comment]
I don't want to ask to use `;;` as I said before. It is too hacky.

**Comment by ko1** [comment]
@st0012 can you accept renaming it to `binding.break` ?

**Comment by st0012** [comment]
> I don't want to ask to use `;;` as I said before. It is too hacky.

how about we keep it as it is and release 1.0 first and let more users decide which way is better? because once the keywords are introduced, it'll be hard to revert it back to the simpler way.

>  can you accept renaming it to binding.break ?

I don't find the renaming necessary but it won't bother me either.

**Comment by ko1** [comment]
1f99707bb5036c8dff25685b2d26860d40e05651
