### ISSUE TITLE
binding.break(do:) doesn't continue in exe/rdbg

### ISSUE THREAD

**Issue by st0012** [ruby/debug#201]
I expect `binding.break(do:)` to continue regardless how I start the debug session. But currently it always stops when used with `exe/rdbg`.

```ruby
# issue.rb
binding.b(do: "p '!!!!!!!!!!!!!!'")
```

### exe/rdbg -e 'c ' issue.rb

```
❯ exe/rdbg -e 'c ' issue.rb
DEBUGGER: Session start (pid: 41207)
[1, 2] in issue.rb
=>    1| binding.b(do: "p '!!!!!!!!!!!!!!'")
      2|
=>#0    <main> at issue.rb:1
(rdbg:commands) c 
[1, 2] in issue.rb
=>    1| binding.b(do: "p '!!!!!!!!!!!!!!'")
      2|
=>#0    <main> at issue.rb:1
(rdbg:commands) p '!!!!!!!!!!!!!!'
=> "!!!!!!!!!!!!!!" 
(rdbg) c # it shouldn't stop here
```

### ruby -Ilib -r debug issue.rb

```
❯ ruby -Ilib -r debug issue.rb
DEBUGGER: Session start (pid: 41237)
[1, 2] in issue.rb
=>    1| binding.b(do: "p '!!!!!!!!!!!!!!'")
      2|
=>#0    <main> at issue.rb:1
(rdbg:binding.break) p '!!!!!!!!!!!!!!'
=> "!!!!!!!!!!!!!!"
```

I guess it's caused by the `PresetCommand` being set not to auto continue when the session is started by `exe/rdbg`. But I don't fully understand the preset command system so I can't fix it.

**Comment by st0012** [comment]
@ono-max is the test framework able to test `exe/rdbg` at the moment?

**Comment by ono-max** [comment]
Currently not supported.

**Comment by st0012** [comment]
@ono-max I see, thanks 👍

**Comment by ko1** [comment]
It's only `-e c` so not high priority issue, I think.

**Comment by st0012** [comment]
@ko1 thanks for the quick fix 👍
