### ISSUE TITLE
Rename trace subcommands

### ISSUE THREAD

**Issue by st0012** [ruby/debug#233]
I'm writing an article about the debugger's tracer feature. And I think we can rename some of the commands to make the concept easier to explain to users.

The current trace commands are:
- `trace line` - `trace <noun>`
- `trace call` - `trace <noun>`
- `trace raise` - `trace <verb>`
- `trace pass` - `trace <verb>`
  - I guess `pass` means "trace how the object is passed in the program" here. So I assume it's used as verb.

As you can see, the parts of speech of subcommands are inconsistent.

Also, each command has its own `Tracer` class, like `LineTracer`. But in the context of naming a class, having a "VerbNoun" combination is usually weird because it feels like the verb is applied to the latter noun. So `RaiseTracer` looks a bit funny to me and I think `ExceptionTracer` would be a better name.

And here are the names I want to propose:

- `trace line` & `LineTracer`
  - When the line is evaluated.
- `trace call` & `CallTracer`
  - When any method is called.
- `trace exception` & `ExceptionTracer`
  - When the exception is raised.
- `trace object` & `ObjectTracer`
  - When the object is passed into a method call as an argument.
  - When the object receives a method call.

In the new names, subcommands are the subject to be traced.
I know `trace object` doesn't convey the `passed as an argument` behavior clearly. But it's not hard to understand either. Also, because no other major Ruby tools have this feature, this project can define what "trace an object" means 🙂

**Comment by ko1** [comment]
`raising` and `passing` were my first idea but I thought they are a bit long and "raise"/"pass" are understandable for users.
I'm okay for `trace exception`, but `trace exceptions` makes sense for me if it should be a noun.
`trace object` is not acceptable because it is unclear what is traced. I guess it should be "object allocation" tracer.

* `trace step/raise/pass` are all verbs.

**Comment by ko1** [comment]
`trace raise` can be removed because `catch Exception do: bt 1` can emulate it.
I implemented it because it seems easy to add. No strong motivation.

**Comment by st0012** [comment]
> trace raise can be removed because catch Exception do: bt 1 can emulate it.

I disagree because:
1. every time a breakpoint is fired (even with `do`), it also prints out surrounded code, which creates noise compare to `trace raise`.
2. it's not easy to remember.

`trace raise` is helpful to monitor exception handling in Rails applications, where there could be multiple exceptions rescued & re-raised. For example:

```
DEBUGGER (trace/raise) #th:1 #depth:220 #<ActiveRecord::RecordInvalid: Validation failed: Email address is already registered. Try logging in or using the password recovery feature.> at /Users/st0012/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4.1/
lib/active_record/validations.rb:80
DEBUGGER (trace/raise) #th:1 #depth:211 #<JSONAPI::Exceptions::ValidationErrors: JSONAPI::Exceptions::ValidationErrors> at /Users/st0012/projects/ticketsolve/app/resources/api/base_resource.rb:294
DEBUGGER (trace/raise) #th:1 #depth:189 #<ActiveRecord::Rollback: ActiveRecord::Rollback> at /Users/st0012/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/jsonapi-resources-0.9.12/lib/jsonapi/acts_as_resource_controller.rb:100
DEBUGGER (trace/raise) #th:1 #depth:182 #<ActiveRecord::Rollback: ActiveRecord::Rollback> at /Users/st0012/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:329
```

> but trace exceptions makes sense for me if it should be a noun.

but we use `trace line` instead of `trace lines`. I think singular noun is appropriate for tracer commands and also saves one key stroke.

how about:

- `trace line`
- `trace exception`
- `trace usage`

**Comment by ko1** [comment]
> trace raise is helpful to monitor exception handling in Rails applications, where there could be multiple exceptions rescued & re-raised. For example:

Good to know.

> trace usage

For me, "usage" is not clear.

**Comment by ko1** [comment]
@mrkn suggested me that `trace call` for `trace pass`.

* `trace call` prints all call (and return?)
* `trace call with: <obj>` is same as `trace pass <obj>`

**Comment by st0012** [comment]
I forgot to add `trace call` to the initial description 🤦 I've added it now.

**Comment by st0012** [comment]
> trace call with: <obj> is same as trace pass <obj>

I don't think it's a good idea because `trace call with: <obj>` gives an impression that it does the same as `trace call` but with a narrower scope. but in fact `trace pass` fires at different timing with different output. so it'd be misleading.

how about `trace occurrence`? and provide `trace o` as a shortcut.

**Comment by ko1** [comment]
I think `trace call_with <obj>` is better.

I'm not sure `occurrence` is fit because I don't think it is only for receiver or parameters (for example, I expect that return values of method call or variable references should be traced).

**Comment by mrkn** [comment]
How about `trace argument <obj>`?

**Comment by st0012** [comment]
I prefer `trace argument <obj>` over `trace call_with <obj>` because it's more consistent with other names.

- `trace line`
- `trace call`
- `trace exception`
- `trace argument`

@mrkn thanks for the suggestion 👍

**Comment by ko1** [comment]
For me `argument` doesn't include receiver...

**Comment by mrkn** [comment]
Why not add `trace receiver`, too?

**Comment by st0012** [comment]
given that printing both the object as receiver & argument is a new behavior (I don't know any tool that offers a similar feature), I think it'll be very hard to come up a single word as a proper name 🤔 

perhaps we can introduce a command that takes `receiver` and `argument` as optional modes? for example,

```
trace object <obj> as: receiver,argument # maybe add return_value when requested?
trace object <obj> # a shortcut for all the available "modes"
trace allocation <obj> # for allocation in the future
```

**Comment by ko1** [comment]
ok, let's try `trace object` (and `exception`).

**Comment by ko1** [comment]
I made a patch, and merge it.

**Comment by ko1** [comment]
369d3c8649c632f8c83bb3669b86fd878b24e1a9

**Comment by st0012** [comment]
@ko1 thanks 👍

**Comment by st0012** [comment]
> BTW trace exception can be accept specific exception like trace exception E. It's futurework.

Does the exception argument need to be evaluated? For exceptions we'll mostly match them with the class instead of a specific exception object. In those cases, I think regexp matching with the exception like https://github.com/ruby/debug/pull/231 would be enough (and perhaps more flexible for exceptions like `ArugmentError`?)

**Comment by ko1** [comment]
ok, let's use pattern until another request.
