### ISSUE TITLE
Integrating ruby/debug with Rails to replace byebug through a single "debugger" call

### ISSUE THREAD

**Issue by dhh** [ruby/debug#261]
Love the progress with this! We'd very much like to make ruby/debug the default debugger in Rails 7. This would replace byebug, which has been the default for 7 years. But to do that, and retain the same developer experience, we're looking for a way to retain a similar interface. 

That means being able to require ruby/debug either all the time or at least all the time in development, and then jumping into the debugger merely by adding a call to "debugger" anywhere in the code base (alternatively using "binding.break", but I find the "debugger" call more intuitive).

Is this approach compatible with the aspirations of ruby/debug? If so, is there anything we can do to help it along, such that we can make the switch for Rails 7?

✌️❤️

**Comment by st0012** [comment]
> That means being able to require ruby/debug either all the time or at least all the time in development, and then jumping into the debugger merely by adding a call to "debugger" anywhere in the code base

Just to share my experience here: my project (Rails 6.1) has installed the debugger for 2 weeks and requires it by default in both development and test environment (even when running on CI). It doesn't break any test case, Rails/Rake task. It also doesn't slow the application in any obvious way. And whenever we need to debug, we just use `binding.b` to enter a debugging session. So I think this is possible already 🙂

**Comment by fxn** [comment]
However, the current implementation assumes that loading the gem means you want to start a session:

```
% ruby -rdebug -e1
DEBUGGER: Session start (pid: 73510)
```

In a Rails application, ideally you'd `require` the gem via Bundler as usual, and have `binding.break` (or whatever) start the session if not already started. I believe this alternative pattern fits better web applications in development. Could be behind a [configuration point](https://github.com/ruby/debug/blob/master/lib/debug/config.rb) for backwards compat (provided that is possible).

**Comment by st0012** [comment]
I see. This is the discussion that led to the current design: https://github.com/ruby/debug/issues/65

From my understanding, debugger session records every iseq sequence that's loaded once it's started.

https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug/session.rb#L86-L89

(which eventually leads to here)
https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug/session.rb#L1304-L1317

So if the debugger session only starts after `binding.b` is called, all the code loaded before it would not be stored into the debugger's [SourceRepository](https://github.com/ruby/debug/blob/c5917c529b/lib/debug/source_repository.rb).


And later affect the source the debugger can retrieve

https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug/session.rb#L265-L271

https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug/frame_info.rb#L62-L64

**Comment by dhh** [comment]
Ah, I just tested this now. It's actually doing the right thing. It doesn't halt execution on require, which is what I thought. So we can just remove `require: false` from the Gemfile.

It does, however, output a noisy "DEBUGGER: Session start (pid: 48334)". Is it possible to turn that off?

**Comment by dhh** [comment]
Also, still wish it was possible to just called "debugger" instead of "binding.b". But that's a minor point.

**Comment by dhh** [comment]
[I've turned it on by default for Rails 7 dev/test](https://github.com/rails/rails/commit/837b0f957715de2db46f2f81d8ac7dccf58a31bd). So this isn't really a problem. Would be nice if there was a way not to get the output statement, and I'd still love "debugger" as an alias for "binding.b", but this is great in any case.

**Comment by rafaelfranca** [comment]
I just investigated this a little bit more. If we require `debug` by default in the Rails framework, and you use the vscode extension (which will call `rdbg`) or use `rdbg` directly you get two debug sessions. The reason for that is that `lib.debug.rb` [starts a session](https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug.rb#L4) and [`rdbg` will start another one](https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/exe/rdbg#L15) requiring `debug/open` or [`debug/start`](https://github.com/ruby/debug/blob/c5917c529b99dee8a7e27ec6abdc2c8e70d4e6f6/lib/debug/start.rb#L5).

Would it possible to not start the session using `ruby -r debug` and always use `ruby -r debug/start`? and only use `debug` to providing the biding methods and setup tracepoint?

**Comment by ko1** [comment]
@rafaelfranca sorry I couldn't catch the points.

`lib/debug.rb` should not be used if
(1) `rdbg` is used
(2) `require 'debug'` with Gemfile and bundle exec.

But `lib/debug.rb` can be required if

(3) `require 'debug'` in Ruby 2.7 or before without Gemfile and bundle exec.

Could you check the situation and make another issue with your reproduce process?

Thanks.

**Comment by ko1** [comment]
Ah, I can repro and make new issue.
