### ISSUE TITLE
Can't use ruby/debug with Ruby 2.6.7?

### ISSUE THREAD

**Issue by brandoncc** [ruby/debug#267]
Thank you for this awesome library, I'm very happy to see this becoming native!

I don't see a Ruby version requirement specified in the documentation, is it usable before Ruby 3.1?

I added debug to my gem file:

```ruby
group :development, :test do
  gem 'debug', '~> 1.0.0'
end
```

and I used it in an rspec test:

```bash
$ rdbg -c  -- bundle exec rspec spec/models/api_wrapper/stripe_spec.rb:80
```

with `binding.break` in my code:

```ruby
require 'debug'; binding.break
expect(sub.status).to eq("trialing")
```

and I get an error about a missing constant:

```
An error occurred while loading ./spec/models/api_wrapper/stripe_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

NameError:
  uninitialized constant DEBUGGER__
# ./config/application.rb:10:in `<top (required)>'
# ./config/environment.rb:3:in `require_relative'
# ./config/environment.rb:3:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `require'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# ./spec/models/api_wrapper/stripe_spec.rb:3:in `require'
# ./spec/models/api_wrapper/stripe_spec.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant DEBUGGER__
#   ./config/application.rb:10:in `<top (required)>'
Run options: include {:locations=>{"./spec/models/api_wrapper/stripe_spec.rb"=>[80]}}
```

**Comment by st0012** [comment]
I can confirm this issue. Thanks for reporting it 👍

**Comment by hsbt** [comment]
Unfortunately, Ruby 2.6 couldn't activate the new debug gem because Ruby 2.6 have old debug library internally.

**Comment by hsbt** [comment]
I think we should specify `required_ruby_version` with Ruby 2.7 or Ruby 3.0.

**Comment by brandoncc** [comment]
Thank you both for the responses, so Ruby 2.7 is the minimum version then?

**Comment by st0012** [comment]
I can reproduce this with `2.7.4` though. I don't think it's a Ruby version issue.

**Comment by st0012** [comment]
@brandoncc since you already has the gem in `Gemfile` you can directly use `binding.b` anywhere in your program and don't need to require it again. So 

```ruby
binding.break
expect(sub.status).to eq("trialing")
```

and 

```
bundle exec rspec spec/models/api_wrapper/stripe_spec.rb:80
```

should work. can you give it a try?

**Comment by brandoncc** [comment]
I only required it the second time because I thought that it wasn't being required when I got the error. I originally had the code as you show it above, without the second require of the gem.

**Comment by st0012** [comment]
The issue is caused by this line: https://github.com/ruby/debug/blob/master/lib/debug/session.rb#L4
I'll fix it today.

**Comment by brandoncc** [comment]
Thank you!

**Comment by hsbt** [comment]
> I can reproduce this with `2.7.4` though. I don't think it's a Ruby version issue.

I did investigate it. Ruby 2.7 also have same status. Only Ruby 3.0 or later have debug.gemspec that is requirement of activate it. I'm not sure how load the different version of old debug lib without the default gems.

**Comment by st0012** [comment]
@hsbt I think is's caused by the debugger's attempt to prevent starting a session inside the bundler. but because `bundle exec` behaves differently between different commands, the approach doesn't work in some cases. I've detailed the problem I see in #269, perhaps you can give some insights?

**Comment by ko1** [comment]
We'll fix this issue as described by @st0012 , but maybe you can try rdbg it now with:

```
$ rdbg -c  -- bundle exec ruby `which rspec` spec/models/api_wrapper/stripe_spec.rb:80
```

**Comment by brandoncc** [comment]
Thank you, I'll give this a shot the next time I need to debug.
