### ISSUE TITLE
debugger method to enter the debug console

### ISSUE THREAD

**Issue by ko1** [ruby/debug#274]
Continue from @dhh issue https://github.com/ruby/debug/issues/261

I'm okay to introduce `debugger` method (`Kernel#`? `Object#`?) if it is de-fact standard method name and there is no conflict with other libraries/applications. debug.gem and byebug may be exclusive so it's doesn't conflict with byebug's method.

Does anyone know the situation of the method name `debugger`?

The reason why I choose `binding.break` is:

1. `Binding` is limited name space and maybe nobody makes `break` method on it (compatibility aspects).
2. People use to type `binding.pry` or `binding.irb` and maybe people are well-trained to type `bidning.` :)
3. (This is technical reason) In future Ruby (maybe JRuby or others already do it) local variables are not stored correctly because of code generation for optimization and `binding` keyword can stop this kind of optimizations. (If `debugger` is also well-known keyword, we can also check this keyword too).

**Comment by st0012** [comment]
I know `debugger` is an official debugging declaration in JavaScript. But in Ruby land I can't re-call seeing any mainstream tool supports that method. Perhaps we can introduce it with the new debugger, and make the cross-language experience consistent? 🤔 

(Personally I still prefer `binding.b` and hope it can be preserved)

**Comment by dhh** [comment]
For Rails, `debugger` had been the default way for the past 7 years when we had byebug. It's not the end of the world, but "binding.break" is just not a very intuitive or handy thing to type. You have to know about a lot of concepts for that to make sense. "debugger" is completely self-explanatory without deep knowledge of Ruby.

**Comment by ko1** [comment]
It is strong that Rails uses `debugger` method name for `byebug`.

**Comment by st0012** [comment]
I didn't know `debugger` can be used to start a byebug session until today 🤯 I always type `byebug` and I'm surprised that it's not mentioned in the [Rails debugging guide](https://guides.rubyonrails.org/debugging_rails_applications.html).

But since `debug.gem` is the successor of `byebug` in Rails, I think this should be supported as well.

**Comment by dhh** [comment]
We really should rewrite that guide now that we have ruby/debug in place as well!

**Comment by st0012** [comment]
@dhh I've been thinking about that as well. `ruby/debug` has several new features that I'd like to mention in the guide.
I plan to work on that after `ruby/debug`'s v1.1.0 is shipped with a bit more features, bug fixes, and perhaps the new `debugger` alias. wdyt?

**Comment by dhh** [comment]
Sounds good 👍

**Comment by ko1** [comment]
BTW I don't think the name `debugger` is straightforward name to open the debug console (I like `Debugger.break` or something if  I can choose any name), but I respect the used tradition.

**Comment by st0012** [comment]
@dhh sorry for the long delay. here's the first batch of document update: https://github.com/rails/rails/pull/43621
