### ISSUE TITLE
Rails server does not start after connecting the debugger

### ISSUE THREAD

**Issue by corocn** [ruby/debug#285]
Hi. I'm trying to debug Rails Application with rdbg and VSCode.

## Issue

Rails server does not start after connecting the debugger. 
rdbg may keep waiting for the debugger connection.

I thought it was just not displayed log, but it does not start actually.

## Log

```
$ rdbg --open --command -- bundle exec rails server

DEBUGGER: can not load newer irb for coloring. Write 'gem "debug" in your Gemfile.
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-63617)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.  # <= attach from VSCode. 
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-63617)
DEBUGGER: wait for debugger connection...
```

---

Server starts correctly without rdbg.

```
$ bundle exec rails server

=> Booting Puma
=> Rails 6.1.4.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 66962
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

---

RSpec works correctly with rdbg.

```
$ rdbg --open --command -- bundle exec rspec spec/requests/xxxx_spec.rb

DEBUGGER: can not load newer irb for coloring. Write 'gem "debug" in your Gemfile.
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-98934)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.

Finished in 0.05668 seconds (files took 2.49 seconds to load)
1 example, 0 failures

Randomized with seed 49662

DEBUGGER: Disconnected.
```

## Version

 - Ruby 3.0.2
 - Rails 6.1.4.1
 - M1 macOS Big Sur 11.5.2
 - VSCode rdbg Ruby Debugger Extension: 0.0.5

launch.json
```json
{
    "type": "rdbg",
    "name": "Attach with rdbg",
    "request": "attach"
}
```

**Comment by st0012** [comment]
I think the correct command should be

```
# need to add --nonstop
rdbg --open --nonstop --command -- bundle exec rails server
```

@ko1 perhaps this line of the vscode extension should be updated? https://github.com/ruby/vscode-rdbg/blob/636388aa96a66fa976afa3a1bc62d370592c682a/src/extension.ts#L308

**Comment by williamhatch** [comment]
@st0012 I met the same issue, even add --nonstop flag, I got the diff errors:
config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)

Version:
1. ruby 2.6.6patch146
2. rails 6.1.4.1
3. MacOs BigSur 11.5.2
4. VSCode rdbg Ruby Debugger Extension: 0.0.5

**Comment by corocn** [comment]
I've made some progress.
After removing bootsnap and Spring, server starts correctly.

The nonstop option was not necessary. Thanks @st0012 

However, it seems that connections are requested twice, and if I attach twice from VSCode, the IDE doesn't show up well even after the break.

```
$ rdbg --command --open -- bundle exec rails server                                                                                                                             

DEBUGGER: can not load newer irb for coloring. Write 'gem "debug" in your Gemfile.
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-49291)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.
DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-49291)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.
=> Booting Puma
=> Rails 6.1.4.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 49291
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

**Comment by williamhatch** [comment]
> I think the correct command should be
> 
> ```
> # need to add --nonstop
> rdbg --open --nonstop --command -- bundle exec rails server
> ```
> 
> @ko1 perhaps this line of the vscode extension should be updated? https://github.com/ruby/vscode-rdbg/blob/636388aa96a66fa976afa3a1bc62d370592c682a/src/extension.ts#L308

@st0012 should not use --nonstop :)... otherwise the program will hang...

**Comment by williamhatch** [comment]
> @st0012 I met the same issue, even add --nonstop flag, I got the diff errors:
> config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
> 
> Version:
> 
> 1. ruby 2.6.6patch146
> 2. rails 6.1.4.1
> 3. MacOs BigSur 11.5.2
> 4. VSCode rdbg Ruby Debugger Extension: 0.0.5

@st0012 ok, i sort it out, it is LOAD_PATH issue.. let me check how to fix that

**Comment by williamhatch** [comment]
> Hi. I'm trying to debug Rails Application with rdbg and VSCode.
> 
> ## Issue
> Rails server does not start after connecting the debugger.
> rdbg may keep waiting for the debugger connection.
> 
> I thought it was just not displayed log, but it does not start actually.
> 
> ## Log
> ```
> $ rdbg --open --command -- bundle exec rails server
> 
> DEBUGGER: can not load newer irb for coloring. Write 'gem "debug" in your Gemfile.
> DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-63617)
> DEBUGGER: wait for debugger connection...
> DEBUGGER: Connected.  # <= attach from VSCode. 
> DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-63617)
> DEBUGGER: wait for debugger connection...
> ```
> 
> Server starts correctly without rdbg.
> 
> ```
> $ bundle exec rails server
> 
> => Booting Puma
> => Rails 6.1.4.1 application starting in development
> => Run `bin/rails server --help` for more startup options
> Puma starting in single mode...
> * Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
> *  Min threads: 5
> *  Max threads: 5
> *  Environment: development
> *          PID: 66962
> * Listening on http://127.0.0.1:3000
> * Listening on http://[::1]:3000
> Use Ctrl-C to stop
> ```
> 
> RSpec works correctly with rdbg.
> 
> ```
> $ rdbg --open --command -- bundle exec rspec spec/requests/xxxx_spec.rb
> 
> DEBUGGER: can not load newer irb for coloring. Write 'gem "debug" in your Gemfile.
> DEBUGGER: Debugger can attach via UNIX domain socket (/Users/xxxxx/.ruby-debug-sock/ruby-debug-xxxxx-98934)
> DEBUGGER: wait for debugger connection...
> DEBUGGER: Connected.
> 
> Finished in 0.05668 seconds (files took 2.49 seconds to load)
> 1 example, 0 failures
> 
> Randomized with seed 49662
> 
> DEBUGGER: Disconnected.
> ```
> 
> ## Version
> * Ruby 3.0.2
> * Rails 6.1.4.1
> * M1 macOS Big Sur 11.5.2
> * VSCode rdbg Ruby Debugger Extension: 0.0.5
> 
> launch.json
> 
> ```json
> {
>     "type": "rdbg",
>     "name": "Attach with rdbg",
>     "request": "attach"
> }
> ```

@corocn it is correct, you need to use rdbg -A to attach, and it works. But I found anther issue
@st0012 @ko1 

The process is attached and works fine, and the console puts like:
DEBUGGER:  BP - Line app/controllers/articles_controller.rb:5 (line) is activated.
DEBUGGER:  BP - Line  app/controllers/articles_controller.rb:6 (line) is activated.

but in the VScode code is not stop there...  Any suggestion? might be extension issue?

**Comment by ko1** [comment]
sorry, the issue contains many logs. Could you give us your current issue with the repro process? Also could you give us your ruby version?

Thanks,
Koichi

**Comment by corocn** [comment]
I'm currently stuck on the same issue as @williamhatch. 
The issue has changed since it was first raised, so I'll reopen the issue.

Thanks
