### ISSUE TITLE
Debug statements randomly skipped when used with multi-process servers

### ISSUE THREAD

**Issue by st0012** [ruby/debug#288]
## Reproduction Setup (with Puma)

1. Add `binding.b` in a controller action:

```ruby
class SomeController < ApplicationController
  def index
    binding.b
    # ....
  end
```

2. Use multiple workers in puma:

```ruby
# config/puma.rb

worker 5 # the bigger the number is, the higher the chance to see this bug
```

3. Start the Rails server
4. Visit the endpoint to see if the breakpoint is triggered. 
  - If it's not, you've hit the bug.
  - If it's triggered, you can restart the server and try again. It usually takes 4, 5 times for me to see it.

## Possible Cause

When the debug statement is called, it checks if the debugger's internal session is active. And it only enters the debugging session if it is.

And when there are multiple processes, the debugger performs deactivates the parent process' session and activates the children's. So if the parent process happen to serve the first request, the debug statement won't be triggered because the process's session is now active.

### 1 request, 1 active session, debugger session started
<img width="80%" alt="截圖 2021-09-16 下午12 51 54" src="https://user-images.githubusercontent.com/5079556/133551644-75528564-f83e-40aa-8722-2458ea2918b2.png">

### 2 requests, 1 active/1 inactive session, debugger session started only once
<img width="690" alt="截圖 2021-09-16 下午12 52 22" src="https://user-images.githubusercontent.com/5079556/133551740-acd7ca58-9777-42dc-83f1-aa7aeed5cede.png">

**Comment by st0012** [comment]
### Context

Every process has a debugger session object (`DEBUGGER__::SESSION`) and it has a boolean `active` state. And when a parent process is forked, its session would be deactivated, while the child process's session would be activated. However, if the parent process' session is already inactivated, this activation/deactivation doesn't happen.

So if process 1 (active) is forked, we'll have:

- Process 1 - debugger session: inactive
- Process 2 - debugger session: active

But if process 1 (inactive) is forked, we'll have:

- Process 1 - debugger session: inactive
- Process 2 - debugger session: inactive

### The Bug

Based on my observation, it happens like this:

1. The main process (process 1) starts, with an active session
2. Process 1 (active) is forked for the first puma worker (process 2), so
    - Process 1 - debugger session: inactive
    - Process 2 - debugger session: active
3. Process 1 (inactive) is forked again for the second puma worker (process 3), so
    - Process 1 - debugger session: inactive
    - Process 3 - debugger session: inactive
4. Eventually, we have 2 puma workers:
    - Process 2 - debugger session: active
    - Process 3 - debugger session: inactive
  
But because process 3's debugger session is inactive, debug statement doesn't trigger in it. Only when the request is served by process 2, the debug statement will be triggered.

**Comment by ko1** [comment]
Only 1 process activates the debug session because if multiple processes activate the sessions and multiple `break` are there, the console mixes the input/output and we can't manage it. It is intentional behavior now.

I want to know how to solve this situation, on the other debuggers for example.
It is possible to open different debug ports for each debuggee (and attach them respectively).

**Comment by ko1** [comment]
Please reopen if it is not fixed.
