### ISSUE TITLE
Save history of commands after finishing the debug session

### ISSUE THREAD

**Issue by marcelolx** [ruby/debug#297]
First of all, thank you all for this debugger, I'm really enjoying it! 👏 

One of the things I miss from byebug is the history of commands (`.byebug_history`), sometimes when debugging some part of a code we have to run a test more than once to understand what's happening, and in those cases sometimes we have to run more commands than a simple `next` or `continue` and then having a history of the commands we've run in the prior session would be really useful.

For example, I was writing a test case for a Rails issue I was checking, but wasn't understanding why the test was passing, to check some information I run `connection.execute "SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name;"`, and in the second time I run the test I touched ⬆️ of my keyboard to select the command but none of the commands I ran in the prior session was suggested, which required to me write the command again.

I would really appreciate it if it would be possible to add this functionality in future versions of  `debug`.

**Comment by st0012** [comment]
### Byebug's Implementation

`byebug` introduced this feature with 3 additional configs:
- `histfile` - the file to store history (`.byebug_history`)
- `histsize` - the number of commands to store in the file
- `autosave` - whether to save history to histfile

And one commnd: `hist[ory] <num>`

Also, history is only saved when the user exists the session.

### Pry's Implementation

`pry` also has 3 configuration options for this

- `Pry.config.history_save` is a boolean option, it defaults to `true`
- `Pry.config.history_load` is a boolean option, it defaults to `true`
- `Pry.config.history_file` is a string option, it defaults to `~/.pry_history`

And a command: `hist[ory]`.

### Potential Implementation for `debug`

#### New Configs

- `history_file` - default is `~/.debug_history`
- `history_size` - default is `1000`
- `history_save` - default is `true`

##### Commands

- `hist[ory]` - list all history commands
- `hist[ory] <num>` - list `<num>` history commands
- `hist[ory] </pattern/>` - filter commands with pattern
- `hist[ory] <num> </pattern/>` - list the first `<num>` of filtered history commands

@ko1 wdyt?

**Comment by ko1** [comment]
it is in TODO
https://github.com/ruby/debug/blob/master/TODO.md#ui

my considerations:

* do you need history command? when do you use it?
* do you need `size`? (why not unlimited?)
* do you need `history_save`? (who want to modify it?)

irb seems to have two configurations:
`IRB.conf[:HISTORY_FILE] = nil`
`IRB.conf[:SAVE_HISTORY] = 1000`

my proposals are:

* `history_file` (default: `~/.rdbg_history`) and nil/empty for disable history feature.
* unlimited history lines
* saved at exit

**Comment by marcelolx** [comment]
Hey @ko1, sorry I didn't see that TODO file

> do you need history command? when do you use it?

I never used history command itself, only through the arrow up.

> do you need size? (why not unlimited?)

I don't have opinions on this, maybe today they have limit on size because it can become slow when there are too many lines? (I suppose that it would need a huge amount of lines to become slow)

> do you need history_save? (who want to modify it?)

I never had seen a reason to modify it.

> my proposals are:
>
> history_file (default: ~/.rdbg_history) and nil/empty for disable history feature.
> unlimited history lines
> saved at exit

+1 from me

**Comment by st0012** [comment]
> * do you need history command? when do you use it?

I don't use it often but I sometimes I use it to recall a Ruby evaluation I used before, for example:

```rb
# make ActiveRecord print sqls to stdout
ActiveRecord::Base.logger = Logger.new($stdout)
```

Its usage is very similar to the `history` command in terminal.

> * do you need `size`? (why not unlimited?)

I'm ok with unlimited size.
> * do you need `history_save`? (who want to modify it?)

I don't disable it. So I guess it's ok to not have it.

> my proposals are:
> 
> * `history_file` (default: `~/.rdbg_history`) and nil/empty for disable history feature.
> * unlimited history lines
> * saved at exit

Sounds good 👍

**Comment by ko1** [comment]
https://github.com/ruby/debug/pull/327

**Comment by marcelolx** [comment]
Thanks! 🎉🚀
