### ISSUE TITLE
Ruby 3.0.2 claims to ship 0.1.0 but 0.1.0 gem has been yanked

### ISSUE THREAD

**Issue by headius** [ruby/debug#298]
This is an out of sync gem change. It is not possible to install the same debug gem as shipped with Ruby 3.0.2.

https://github.com/ruby/ruby/blob/ruby_3_0/lib/debug.gemspec#L3

The 0.1.0 gem has been yanked.

**Comment by headius** [comment]
The resolv library has a few tweaks for JRuby that may or may not be things we can fix.

Diffs are here: https://gist.github.com/headius/6508dfe066630bfa42e4d53b70c9c72e

**Comment by hsbt** [comment]
I yanked debug-0.1.0 because it's the different implementation with ruby/debug. I will backport debug-0.2.0 to Ruby 3.0.3 at https://github.com/ruby/ruby/pull/5104/commits/b5e338f97e264aee7ecd87616838a63ad06f85d3.

You can use debug-0.2.0 at https://github.com/ruby/debug/releases/tag/v0.2.0
