### ISSUE TITLE
Plans to support stdio?

### ISSUE THREAD

**Issue by olimorris** [ruby/debug#323]
I wondered if there are any plans to support `stdio`?

As per a discussion I was having [here](https://github.com/mfussenegger/nvim-dap/issues/329) on the popular Neovim debugger plugin, `nvim-dap`, a lot of debuggers seem to work over `stdio`, `tcp/ip` but not sockets. So wondering if this is on the roadmap?

As an aside, I'm presume I could get `rdbg` running locally and attach to it via `tcp/ip`?

**Comment by mfussenegger** [comment]
> For DAP, the problem is how to handle programs input/output on stdio.
There is output event https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output but I can't find how to handle input.

From what I've seen most debug adapters just don't support stdin for programs if the debug adapter itself is using DAP over stdio.
An exception is codelldb, which lets users configure redirection targets via properties in the `launch` configuration: https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#stdio-redirection

**Comment by ko1** [comment]
> An exception is codelldb, which lets users configure redirection targets via properties in the launch configuration: https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#stdio-redirection

Ah, I see.

**Comment by ko1** [comment]
Could you try with TCP/IP?
Please reopen this if someone want to use stdio except that.

**Comment by olimorris** [comment]
Sorry. I should have added that it works great with TCP/IP

**Comment by will** [comment]
The problem I'm having with TCP is that you then cant set any breakpoints because of 

```
  def dap_setup bytes
      CONFIG.set_config no_color: true
      @seq = 0

      case self
      when UI_UnixDomainServer
        UI_DAP.local_fs_map_set true
      when UI_TcpServer
        # TODO: loopback address can be used to connect other FS env, like Docker containers
        # UI_DAP.local_fs_set if @local_addr.ipv4_loopback? || @local_addr.ipv6_loopback?
      end

```

**Comment by ko1** [comment]
@will Could you tell the your repr- steps? Are you using nvim?

**Comment by will** [comment]
Hi @ko1 ひさしぶり :)

Sorry I forgot to come back to this issue. I figured out from reading the source that if you send "localfs=true" as part of the attach request, then you can use breakpoints.

I am using neovim, this is my entire current setup:

```lua
local use = require("packer").use
use "mfussenegger/nvim-dap" 
use "rcarriga/nvim-dap-ui" 
use "theHamsta/nvim-dap-virtual-text"

local dap = require "dap"

dap.adapters.ruby = function(callback, config)
  callback {
    type = "server",
    host = "127.0.0.1",
    port = "${port}",
    executable = {
      command = "bundle",
      -- stylua: ignore
      args = { "exec", "rdbg", "-n", "--open", "--port", "${port}",
        "-c", "--", "bundle", "exec", config.command, config.script,
      },
    },
  }
end

dap.configurations.ruby = {
  {
    type = "ruby",
    name = "debug current file",
    request = "attach",
    localfs = true,
    command = "ruby",
    script = "${file}",
  },
  {
    type = "ruby",
    name = "run current spec file",
    request = "attach",
    localfs = true,
    command = "rspec",
    script = "${file}",
  },
}
```

Plus some keybindings, but those aren't important. Everything has been working great with this! 

The virtual text plugin is particularly neat. It uses tree-sitter to know where local are defined, then shows the current values of variables where they live 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/1973/181182732-89cdd25b-ca87-4b7e-8148-08b9fd16e58f.png">

**Comment by ko1** [comment]
お久しぶりです！

That is great you can achieve. 
I'm completely newbe of neovim, but should I put your configs to ~/.config/nvim/... ?

**Comment by will** [comment]
Configs for neovim go in `~/.config/nvim/` by default, yes. It follows the XDG_ home direcotry things. So I tried to make this a minit config that is simple to do a first install for you to try.

In the video I'm changing all of the XDG_ directories to my temp dir to not conflict with my "real" config. You can set all the env vars too if you want, or just ignore them and have this as your nvim config in `~/.config/nvim`. Either should be okay.


```lua
-- init.lua

-- packer setup
local fn = vim.fn

-- auto install packer if missing
local install_path = fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
  fn.system { "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path }
end

local ok, packer = pcall(require, "packer")
if not ok then
  vim.notify "just installed packer, please quit nvim and reopen"
  return
end

packer.init()
-- end packer setup


-- install plugins
local use = packer.use
use "wbthomason/packer.nvim"
use "mfussenegger/nvim-dap"
use "rcarriga/nvim-dap-ui"
use "theHamsta/nvim-dap-virtual-text"
-- this one is just for nicer colors
use {
  "rose-pine/neovim",
  as = "rose-pine",
  config = function()
    local ok, rp = pcall(require, "rose-pine")
    if ok then
      rp.setup()
      vim.cmd "colorscheme rose-pine"
    end
  end,
}
-- end install plugins


-- DAP setup
local ok, dap = pcall(require, "dap")
if not ok then
  -- I wouldn't normally do it this way, just to make it easier to test out neovim
  -- run packer sync if plugins are missing
  packer.sync()
  vim.notify "Plugins installed, please quit and reopen neovim"
  return
end

dap.adapters.ruby = function(callback, config)
  callback {
    type = "server",
    host = "127.0.0.1",
    port = "${port}",
    executable = {
      command = "bundle",
      args = { "exec", "rdbg", "--open", "--port", "${port}", "-c", "--", config.command, config.script },
    },
  }
end

dap.configurations.ruby = {
  {
    type = "ruby",
    name = "debug current file",
    request = "attach",
    localfs = true,
    command = "ruby",
    script = "${file}",
  },
}
-- end dap setup

-- dap ui is extra, you don’t need it but it's nice
local dapui = require "dapui"
dapui.setup()
-- these aren't necessary but make the dap ui just pop up automatically which is neat
dap.listeners.after.event_initialized["dapui_config"] = dapui.open
dap.listeners.before.event_terminated["dapui_config"] = dapui.close
dap.listeners.before.event_exited["dapui_config"] = dapui.close
-- end dap ui

require("nvim-dap-virtual-text").setup()

--keymaps
local set = vim.keymap.set
--Remap space as leader key
set("", "<Space>", "<Nop>")
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- these are just a few to make things nice
-- you can run any dap function with 
-- :lua require'dap'.the_function()
-- inside nvim if you don’t map it
set("n", "<leader>c", dap.continue)
set("n", "<leader>s", dap.step_over)
set("n", "<leader>b", dap.toggle_breakpoint)
```

then start neovim one time, it should install packer. quit neovim
start neovim a second time, it should use packer to install all the plugins. quit neovim
now every time neovim should have the plugins, you can edit a ruby file and debug

Here is a demo video:



https://user-images.githubusercontent.com/1973/181347365-d1b961f3-8482-46ed-94b8-a3e62858412e.mp4

**Comment by olimorris** [comment]
@will, FYI, I have RSpec debugging for the current line I'm on:

```lua
  dap.adapters.ruby = function(callback, config)
    local script

    if config.current_line then
      script = config.script .. ":" .. vim.fn.line(".")
    else
      script = config.script
    end

    callback({
      type = "server",
      host = "127.0.0.1",
      port = "${port}",
      executable = {
        command = "bundle",
        args = { "exec", "rdbg", "--open", "--port", "${port}", "-c", "--", config.command, script },
      },
    })
  end

  dap.configurations.ruby = {
    {
      type = "ruby",
      name = "debug rspec current_line",
      request = "attach",
      localfs = true,
      command = "rspec",
      script = "${file}",
      current_line = true,
    },
    {
      type = "ruby",
      name = "debug current file",
      request = "attach",
      localfs = true,
      command = "ruby",
      script = "${file}",
    },
  }
```
