### ISSUE TITLE
Use with foreman and remote debugger

### ISSUE THREAD

**Issue by acetinick** [ruby/debug#328]
Hi, 

I am looking to use this library to integrate with our local dev environment using foreman.   I read in another issue #287 that we could use debug gem as a remote debugger, but unsure if I am doing it the right way.  

My procfile
```
web: rdbg -O -- bundle exec rails s
worker: bundle exec sidekiq -C config/sidekiq.yml
webpacker: WEBPACKER_DEV_SERVER_HOST=0.0.0.0 ./bin/webpack-dev-server
```

But I get the following error:

web-1            | 19:23:04 web.1       | /usr/local/bin/ruby: No such file or directory -- bundle (LoadError)

**Comment by ko1** [comment]
Not released yet. You can try it on master branch.

**Comment by jon-sully** [comment]
This gem is awesome. Working through the Rails 7 upgrade and loving `debug` so far. +1 for the `debugger` alias ❤️ 

I got remote debugging with Foreman / Procfile up and running pretty smooth (for what I wanted) and thought I'd share. I didn't change the `web:` declaration in my procfile; I prefer to keep my procfile clean (even though it's a .dev, still) — I instead just add `require 'debug/open_nonstop'` to the top of my `development.rb` config file (with a note about why it's there for my fellow devs) then run the application with Foreman as normal. At that point I can use the VS Code adapter to attach to the process at any time and have a live debugging connection or, more typically, after dropping in a `debugger` and forcing the breakpoint, attach to the process to work through that debugging point.

Works excellently! Probably the best IDE-driven debugging process I've ever had in Ruby 😆 Thank you team!!

**Comment by ko1** [comment]
@acetinick sorry for absent.

I'm not sure why Gmefile.lock specifies 1.2.4. Do you have an idea? (I'm not an expert about bundler ecosystem).

**Comment by jpau-besmartee** [comment]
@jon-sully 
I have recently been trying to get the `require 'debug/open_nonstop'` working in my rails application (using foreman as well). However when I add the line to the top of my `development.rb` my application loads as if it is never loaded. For comparison, if I add that same line to the top of my `bin/rails` file then it will start up and my console says:
```
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-0/ruby-debug-ruby-debug-10)
```

Does this still work for you or have you had to make any updates to get your debugger to work?

**Comment by elalemanyo** [comment]
> This gem is awesome. Working through the Rails 7 upgrade and loving `debug` so far. +1 for the `debugger` alias ❤️
> 
> I got remote debugging with Foreman / Procfile up and running pretty smooth (for what I wanted) and thought I'd share. I didn't change the `web:` declaration in my procfile; I prefer to keep my procfile clean (even though it's a .dev, still) — I instead just add `require 'debug/open_nonstop'` to the top of my `development.rb` config file (with a note about why it's there for my fellow devs) then run the application with Foreman as normal. At that point I can use the VS Code adapter to attach to the process at any time and have a live debugging connection or, more typically, after dropping in a `debugger` and forcing the breakpoint, attach to the process to work through that debugging point.
> 
> Works excellently! Probably the best IDE-driven debugging process I've ever had in Ruby 😆 Thank you team!!
> 
> **EDIT:** I may in the future switch from having the `require 'debug/open_nonstop'` in `development.rb` to just making my Procfile.dev's `web` command be `rdbg -O -n -c bundle exec puma` since the `development.rb` require approach can make certain commands finicky. Time will tell. Both work great 🙂

@jon-sully can you explain how you can attach to the process of a `debugger`, maybe also without using VC 😬
Thanks

**Comment by jon-sully** [comment]
Ah, yeah that's uh.. relevant! 😆 "Here's how to fire up the debugger" without "here's how you connect" feels a little half-baked. Sorry!

You can connect to the running ruby (web) process once it's fired up (as long as you wrap it in Rdbg via my prior comment) either via VS Code with a `launch.json` config like:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach"
    }
  ]
}
```

Provided you have the Ruby VS Code extension installed (https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby)

Or you can connect directly to the process via command line by just running:

```bash
$> rdbg -A
```

Which is the short hand for "attach".

Attaching to a running process should work whether that process is currently paused at a break point _or_ running normally.

**Comment by jon-sully** [comment]
> @jon-sully I have recently been trying to get the `require 'debug/open_nonstop'` working in my rails application (using foreman as well). However when I add the line to the top of my `development.rb` my application loads as if it is never loaded...
>
> Does this still work for you or have you had to make any updates to get your debugger to work?

@elalemanyo I can't recall exactly why I switched to using the CLI invocation instead of the ruby package — I think I was getting a bit of strange behavior too, but I have been using this for most of the year with my `Procfile.dev` set as:

```procfile
# NOTE: Opens up the remote debugging back-door port so that when a breakpoint
# is hit in the server process (running under Foreman), a remote debugging
# utility (https://marketplace.visualstudio.com/items?itemName=KoichiSasada.vscode-rdbg
# for VSCode) (`rdbg -A` in a terminal) can attach and control/continue/etc. Neato!
web: rdbg -O -n -c bundle exec puma

log: tail -f -n 0 log/development.log
js: yarn build --watch
css: yarn build:css --watch
```

And boot the application using Rails 7's canonical `bin/dev`.

**Comment by elalemanyo** [comment]
@jon-sully Normally I was starting my web service using this: `web: bin/rails server -p $PORT -b $BIND
`, so now following your instructions I am using `web: rdbg -O -n -c bin/rails server -p $PORT -b $BIND` but I am getting this error:

<img width="1154" alt="shot2022-10-14 at 13 48 41@2x" src="https://user-images.githubusercontent.com/3856862/195839870-2473f54f-9b4a-4140-a1c3-07c6cae2bcfd.png">

any idea? Thanks

**Comment by st0012** [comment]
Try this: `rdbg -O -n -c -- bin/rails server -p $PORT -b $BIND`

**Comment by elalemanyo** [comment]
@st0012 thanks for your suggestion, now I get a new error 🙂

<img width="1426" alt="shot2022-10-14 at 13 59 38@2x" src="https://user-images.githubusercontent.com/3856862/195841905-bb6f1526-2877-4514-9db9-d42b56061ca8.png">

Not sure if now is because of my setup... I keep trying 💪

**Comment by st0012** [comment]
Add `bundle exec` before both `rdbg` and `bin/rails` should help.

**Comment by jon-sully** [comment]
I too am on the "always bundle exec before ruby executables" train 😛 as with the common / idiomatic `be` prefix shortcut.

**Comment by elalemanyo** [comment]
@st0012 thanks again but getting new error 😬

<img width="1326" alt="shot2022-10-14 at 14 41 39@2x" src="https://user-images.githubusercontent.com/3856862/195849584-4d254f87-6cfd-4458-92af-82445545a1e0.png">

**Comment by jon-sully** [comment]
Try this :)

```bash
bundle exec rdbg -O -n -c -- bundle exec rails s -p $PORT -b $BIND
```

**Comment by st0012** [comment]
Can you upgrade debug to the latest version? It looks like a bug I fixed in 1.6.*.

**Comment by elalemanyo** [comment]
@st0012 now works! To connect to debugger I can run `rdbg -A` in a terminal, right? Trying this but having some issues... running all my setup inside docker so I am running `docker exec -it <mycontainer> rdbg -A` but I am getting this error:
<img width="1145" alt="shot2022-10-14 at 15 42 47@2x" src="https://user-images.githubusercontent.com/3856862/195861726-16738809-f572-4201-9777-a6bc2fefd98e.png">

**Comment by jon-sully** [comment]
I'm not a docker / container user myself but does `docker exec -it` run that command inside the same container, or just spin up a new small container to run the following command? If it's the latter then I'd imagine you'll have to figure out how to expose the right socket / port info so that a different container can connect to your server container. This is all outlined pretty well in the docks for ["Remote Debugging"](https://github.com/ruby/debug#remote-debugging) on the README. 

I'll probably leave my thoughts at that for containerized running though — just want to stay true to the topic of this particular issue we're commenting on (which is just how to use Ruby Debug as a remote client for when running Rails Server under Foreman). Cheers! 👍

**Comment by elalemanyo** [comment]
@st0012 `docker exec command` runs a new command in a running container, so that should be ok. But you're right that this is off topic, sorry about that. Thanks for all the help.

**Comment by spovich** [comment]
@elalemanyo I just stumbled on this issue. I think the problem you are having is the parser doesn't recognize that the `-p` and `-b` are for the `bin/rails` command and not `rdbg`.  Just put the `-c` command in quotes and it is works for me:

```
web: rdbg -O -n -c "bin/rails server -p $PORT -b $BIND"
```

**Comment by nimmolo** [comment]
Thanks everybody for the help here. 

None of these solutions worked for me, including @spovich 's most recent. What worked for me was cutting the `web:` line with `rails server` entirely out of my `Procfile.dev` and just running the server in another window with `rails s` the old way. So my `foreman` is only running `dartsass`, `solid_queue`, `actioncable` and whatever other processes, and the window running `rails s` works as expected with `debug`. 

Setting up a port for `debug` and starting `rdbg` in another window, even if it weren't so buggy, is certainly not easier — and frankly seems a little convoluted. If `foreman` and `debug` are both core Rails now, it seems like a debug session is something that should work out of the box (I realize this is the wrong repo to say that!). It should really require no time or research to set up, and it should be well documented. right?
