### ISSUE TITLE
Errno::EMFILE: Too many open files

### ISSUE THREAD

**Issue by andrewmarkle** [ruby/debug#362]
**Your environment**

* `ruby -v`:  ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]
* `rdbg -v`: rdbg 1.3.4

**Describe the bug**
We installed the gem into our Rails app (v 6.1.4.1) and shortly after people began to experience the following error:

```
Errno::EMFILE: Too many open files 
```

![stack trace](https://user-images.githubusercontent.com/2506835/139859182-49df8fb6-25fd-4ce2-91b6-86d4a8d831c3.jpeg)

For some people this would happen every other request in development and they would have to restart their Rails server (we use the latest version of Puma) to continue working. For others it wouldn't happen at all or would only happen sporadically. 

It took us a while to figure out that the debug gem was responsible. Removing the gem made the issue go away.

**To Reproduce**
This is pretty tricky to reproduce. We had a couple people who could reproduce this bug in our application consistently. For others it would happen once-and-a-while or not at all depending on their activity. Very difficult to narrow down unfortunately. We only discovered that the debug gem was responsible after extensively combing through our git history.

**Expected behavior**
This error should not happen.

**Additional context**
Let me know if you have any further questions. Would love to help in any way. I love this debugger and really want to use it! Thank you so much!

**Comment by ko1** [comment]
do you use local REPL or remote debuggers?

**Comment by andrewmarkle** [comment]
Local REPL but that has been happening without any `binding.break`
inserted. We do have pry and pry-rails in our Gemfile though.

On November 4, 2021, Github Notification ***@***.***>
wrote:
> do you use local REPL or remote debuggers?
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ruby/debug/issues/362#issuecomment-961459355>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AATEAU6YEA4H36RHCML4CXTUKL6ANANCNFSM5HGQGILQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by ko1** [comment]
could you share the `lsof` output when the EMFILE exception is raised?

**Comment by andrewmarkle** [comment]
Thanks @ko1. I sent you an email.

**Comment by ko1** [comment]
@andrewmarkle sent me a lsof log but I couldn't find how to solve it.
Maybe it is hard to solve this issue without the repro-code, so please reopen if someone share a small (or easy to setup) repro code.

Sorry for absent.
