### ISSUE TITLE
Support for fish for `rdbg --util=init -`

### ISSUE THREAD

**Issue by dorianmariefr** [ruby/debug#377]
**Your environment**

* `ruby -v`: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
* `rdbg -v`: rdbg 1.3.4

**Describe the bug**

I'm trying to have `debugger` available in all my gems and apps when debugging, so I would like to use the init feature, but I'm using fish and have to do it manually:

```
set -x RUBYOPT "-r /Users/dorianmariefr/.rvm/gems/ruby-3.0.2/gems/debug-1.3.4/lib/debug/prelude" $RUBYOPT
```

**To Reproduce**

`eval (rdbg --util=init -)` in a fish shell

**Expected behavior**

it works and preloads debug gem

**Comment by ko1** [comment]
Ah, you mean `fish` doesn't supporet `export` like bash?
Do you know how to write this kind of configurations? (I only use bash, so I don't know the general solution).

**Comment by ko1** [comment]
can we recognize it is on a fish shell or bash etc?

**Comment by dorianmariefr** [comment]
it seems very complicated:

- `$SHELL` gives the user's preferred shell, not the current shell
- `$BASH_VERSION`, `$FISH_VERSION`, etc. are available in the terminal but not from the ruby script

**Comment by ko1** [comment]
rbenv does:
https://github.com/rbenv/rbenv/blob/585ed84283f3308380b843391ee7b12706ecff87/libexec/rbenv-init#L9-L18

wow.

**Comment by ko1** [comment]
sorry here:
https://github.com/rbenv/rbenv/blob/585ed84283f3308380b843391ee7b12706ecff87/libexec/rbenv-init#L34-L42

**Comment by ko1** [comment]
another example @hsbt told me:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.sh#L19

and it seems enough:

```
case `ps -p #{Process.ppid} -o 'args='`
when 'fish'
  p :fish
when /csh/
  p :csh
when /bash/
  p :bash
...
end
```

**Comment by dorianmariefr** [comment]
ah okay didn't know about PPID (parent process ID), looks cool, takes 6-8ms on my machine:

```
starting = Time.now
case `ps -p #{Process.ppid} -o 'args='`
when /fish/
  p :fish
when /csh/
  p :csh
when /bash/
  p :bash
end
ending = Time.now
puts ending - starting
```

**Comment by dorianmariefr** [comment]
I added automatic detection of fish, should I add support for `csh | -csh | tcsh | -tcsh)`?

**Comment by ko1** [comment]
if you can. But I don't use them so I can't review it :p

**Comment by dorianmariefr** [comment]
hmmm I tried (and I discovered a bug on bash, `$(RUBYOPT)` would not work on my bash, but I was getting `sh` on `csh` and not sure how to do setenv, I would rather someone using it add it

**Comment by JoshCheek** [comment]
Fish does have an export command (https://github.com/fish-shell/fish-shell/blob/master/share/functions/export.fish), but it doesn't do whatever the subshell thing is called (command substitution?). But then again... it sseems like we want to interpolate a variable, not execute a command. Eg I don't think the existing implementation works in bash, either. Seems like if we delete the parentheses, it will work in both bash and fish:

(note this example is in fish)

```fish
# The shell output
$ rdbg --util=init -
export RUBYOPT="-r /Users/josh/.gem/ruby/3.0.2/gems/debug-1.3.4/lib/debug/prelude $(RUBYOPT)"

# Doesn't work in bash, b/c it's trying to execute RUBYOPT as a program
$ bash -c (rdbg --util=init -)
bash: line 1: RUBYOPT: command not found

# Doesn't work in fish b/c Fish doesn't have a special syntax for command substitution
$ fish -c (rdbg --util=init -)
fish: $(...) is not supported. In fish, please use '(RUBYOPT)'.
export RUBYOPT="-r /Users/josh/.gem/ruby/3.0.2/gems/debug-1.3.4/lib/debug/prelude $(RUBYOPT)"

# The existing code (ag is basically grep)
$ ag RUBYOPT (gem which debug/client)
27:            export RUBYOPT="-r #{__dir__}/prelude $(RUBYOPT)"

# Delete the parens
$ ruby -i -pe '$_.delete! "()" if /RUBYOPT/' (gem which debug/client)

# The modified code
$ ag RUBYOPT (gem which debug/client)
27:            export RUBYOPT="-r #{__dir__}/prelude $RUBYOPT"

# Now it works in bash
$ bash -c (rdbg --util=init -)'; echo $RUBYOPT'
-r /Users/josh/.gem/ruby/3.0.2/gems/debug-1.3.4/lib/debug/prelude

# And in fish
$ fish -c (rdbg --util=init -)'; echo $RUBYOPT'
-r /Users/josh/.gem/ruby/3.0.2/gems/debug-1.3.4/lib/debug/prelude
```

**Comment by dorianmariefr** [comment]
Nice @JoshCheek, I didn't know fish had an `export` function

**Comment by dorianmariefr** [comment]
I'm not sure about keeping the `set -x` or doing `export` but we would need to detect fish because `eval $(...)` doesn't work on fish, it's `eval (...)`

**Comment by JoshCheek** [comment]
I guess the `eval (rdbg --util=init -)` is probably more dynamic, and thus more able to handle unexpected future use cases. But it's not something that I would personally use, because it might add ~100ms each time I start a new shell. What I do in these cases is run the underlying command and then paste that into the shell. At the end of the day, all it needs to do is set the env var, which is negligibly cheap. Launching Ruby and requiring files to figure out that it needs to set the env var is relatively more expensive, and if you get a few different apps that want to do this (eg homebrew likes to do it, too), then they can add up to be quite a bit.

I'm not saying we should change it, just that this is what makes the most sense to me b/c it reduces shell startup time, unifies the shell syntax, and removes the seemingly difficult problem of determining the user's shell. And while it is less dynamic, it seems unlikely to be problematically so (realistically, I think it would only be an issue if it needed to set another env var, which just doesn't seem very likely).

**Comment by dorianmariefr** [comment]
right, even without the shell detection it takes `253.98 millis`, not sure how we could improve that.

the issue with adding the full path directly is that there is the ruby version and the gem version in the path directly so it might break after some upgrades or some cleaning

**Comment by ko1** [comment]
Thank you the discussion.

I write `export RUBYOPT="-r /mnt/c/ko1/src/rb/ruby-debug/lib/debug/prelude $RUBYOPT"` directly, it is safe because it is cloned ruby/debug source code :p
Anyway, do we have good solution...?

**Comment by dorianmariefr** [comment]
@ko1 what's wrong with this pull request? https://github.com/ruby/debug/pull/383

**Comment by ko1** [comment]
https://github.com/ruby/debug/pull/428 does not run ruby in load script.

**Comment by dorianmariefr** [comment]
@ko1 but then there is the ruby version and the gem version in the shell config file, meaning that would need to be updated for each ruby upgrade and each gem upgrade

**Comment by ko1** [comment]
Yes, exactly. This is current limitation.
