### ISSUE TITLE
Debug on arbitrary binding

### ISSUE THREAD

**Issue by svoop** [ruby/debug#390]
To facilitate frequent debugging on a tool, I'm trying to implement a simple version of `pry-rescue` for debug.

Using the [interception gem](https://github.com/ConradIrwin/interception), it looks something like this:

```ruby
require 'debug'
require 'interception'

class Executable
  def run
    intercept do
      fail "foobar"
    end
  rescue => error
    intercept error
  end

  private

  def intercept(error=nil, &block)
    if error
      @interceptions[error].break
    else
      Interception.listen(block) { |e, b| (@interceptions ||= {})[e] = b }
    end
  end
end

Executable.new.run
```

Save the above to `test.rb` and then run it with `ruby test.rb`.

The debugger opens a session always in the context of the line where `break` is sent:

```
    12|
    13|   private
    14|
    15|   def intercept(error=nil, &block)
    16|     if error
=>  17|       @interceptions[error].break
    18|     else
    19|       Interception.listen(block) { |e, b| (@interceptions ||= {})[e] = b }
    20|     end
    21|   end
```

However, if I change line 17 to `@interceptions[error].irb`, the IRB session is opened in the context of the actual error:

```
     2: require 'interception'
     3:
     4: class Executable
     5:   def run
     6:     intercept do
 =>  7:       fail "foobar"
     8:     end
     9:   rescue => error
    10:     intercept error
    11:   end
    12:
```

Is this the intended behavior or is it / should it be possible to start a debugger session on any binding?

**Comment by ko1** [comment]
No. `binding` doesn't have enough information to start debugger console.
