### ISSUE TITLE
show_src_lines parameter is not used in list(ing)

### ISSUE THREAD

**Issue by chdimitrov** [ruby/debug#402]
Hello debug team 
I am checking your new gem which I like very much. I didn't know how to categorize the question so I am posting it as open one
Currently I have set config in **.rc** file for **show_src_lines** to be **20**
and somehow I was expecting(intuition) that when I try to list (with '**l**')
that i will see result of **20** rows not the default **10
as it looks it really show the parametrized rows on a breakpoint 
but can this be made to work for listing or to add another config parameter for listing too as I find it useful from my point of view
![Screenshot from 2021-11-19 20-29-54](https://user-images.githubusercontent.com/2130515/142673454-68094112-4291-41ed-af1c-496a309e35e2.png)
**

**Comment by st0012** [comment]
yeah I also think `show_src_lines` should be applied on the `list` command. wdyt? @ko1
