### ISSUE TITLE
Configuration variable to disable debug

### ISSUE THREAD

**Issue by alexeyschepin** [ruby/debug#416]
Hi. I have just recently started to use ruby debug. It works like a charm but I have a question.
How can I disable debug for certain cases?

I want to use it only for my local debugging. My jenkins pipeline runs rspec tests before deploying a new release. I'd like to disable debug at this point. How can I do it?

My `Gemfile`
```ruby
group :development, :test do
  gem 'debug', '>= 1.0.0'
  ...
end
```

Is there a variable like `RUBY_DEBUG_ENABLE` that I can set to `false`?
Or should I remove `debug` from the Gemfile and install it rather globally?
Is there any other solution you could recommend me?

Thank you

**Comment by st0012** [comment]
The debugger currently doesn't have support for this. What I have in my project looks like this:

```rb
gem "debug", require: ENV["ENABLE_DEBUG"] == "1"
```

**Comment by alexeyschepin** [comment]
@st0012 thanks, this is a nice workaround.

**Comment by ko1** [comment]
just my curious, do you run your test on `development`?

**Comment by alexeyschepin** [comment]
@ko1 no, it is on test, but I want to be able to debug both test and development environments.

**Comment by ko1** [comment]
Ah, one more. Now.`require 'debug'` only add some code and hooks to track the loaded programs. I think it doesn't affect the application.
Why do you want to disable everything?

**Comment by alexeyschepin** [comment]
I expected it might slowdown execution.
The main reason was spamming logs in my cucumber tests with 

```
DEBUGGER: Attaching after process 7 fork to child process 14
    can display the compliance check
  with a failed compliance check

DEBUGGER[/usr/local/bundle/bin/rspec#102]: Attaching after process 7 fork to child process 102
    can display the compliance check

Pages::Abc::Page
  with investigation
DEBUGGER[/usr/local/bundle/bin/rspec#189]: Attaching after process 7 fork to child process 189
```

**Comment by ko1** [comment]
Ah, I see.

`RUBY_DEBUG_DISABLE=1 ...` will help you?

**Comment by ko1** [comment]
or `RUBY_DEBUG_ENABLE=0` (default: 1)

**Comment by alexeyschepin** [comment]
@ko1 yes, it would be perfect!

**Comment by ko1** [comment]
Now simple `RUBY_DEBUG_ENABLE` is supported.
`RUBY_DEBUG_ENABLE=0 ...` will disable the debugger features.
