### ISSUE TITLE
binding.bp with commands

### ISSUE THREAD

**Issue by st0012** [ruby/debug#43]
Many developers, including me, usually enter debugging session with a method call like `byebug` or `binding.pry`. So we'd mostly use `binding.bp` instead of the `rdbg` executable when using this tool. 

But unlike the `rdbg` executable, which can take a series of commands with the `-e` option, `binding.bp` doesn't take any arguments or options. So I'm wondering if we can support passing commands to it like:

```ruby
binding.bp(command:  "c ;; bt ;; info")
binding.bp(command_file: "foo.rb")
```

**Comment by ko1** [comment]
`command:` seems good idea.
Maybe `command_file:` is too much...

**Comment by ko1** [comment]
BTW there is objection to the name `binding.bp` https://bugs.ruby-lang.org/issues/17863#note-2

So I'm thinking to rename it to `binding.debug`. What do you think about it?

**Comment by st0012** [comment]
I'd prefer having both. `binding.debug` is too long for me and I don't find `binding.bp` confusing so I'd be happy to use it.
