### ISSUE TITLE
"undefined method '+' for nil" in postmortem console with use_short_path

### ISSUE THREAD

**Issue by svoop** [ruby/debug#436]
**Your environment**

* `ruby -v`: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
* `rdbg -v`: rdbg 1.3.4

**Describe the bug**
With `use_short_path: true`, the postmortem console trips over a "undefined method '+' for nil" exception which traces back to [this line of code](https://github.com/ruby/debug/blob/5af5618f51e32ee2772d3d6ca872be952679447c/lib/debug/frame_info.rb#L34): `CONFIG["rubylibdir"]` is nil.

**Additional context**
* OS: macOS 12.1 (Apple Silicon)
* Homebrew: Homebrew 3.3.7
* Ruby installed with [ruby-install](https://github.com/postmodern/ruby-install) and switched with [chruby](https://github.com/postmodern/chruby)

**Comment by st0012** [comment]
@svoop thanks for reporting the issue. I've added https://github.com/ruby/debug/pull/437 for it 🙂

**Comment by svoop** [comment]
@st0012 Wow, thanks for the really quick fix!
