### ISSUE TITLE
debug question

### ISSUE THREAD

**Issue by kaiquekandykoga** [ruby/debug#443]
Hello guys,

Is it possible to use [debug](https://github.com/ruby/debug) to debug itself?

I am currently using other debugger tools to understand the [debug](https://github.com/ruby/debug) source code.

I am curious to know how you guys debug the code.

Thank you very much.

**Comment by st0012** [comment]
I only use `p` or `pp`. I avoid `puts` because some components like `ThreadClient` implements the `puts` method as well. And in most conditions `binding.irb` can also work.

**Comment by kaiquekandykoga** [comment]
Hello @st0012 ,

I appreciate the time used to answer.

I will try your approach.

Thank you very much.
