### ISSUE TITLE
Exceptions inside frame inspection are fatal

### ISSUE THREAD

**Issue by adam12** [ruby/debug#45]
I'm really not sure if this is a bug, but I presume it is. The example is contrived, but I was able to trigger this by putting `URI` in a strange state (for which I was debugging :joy:).

Target
```ruby
class Baz
  Error = Class.new(StandardError)

  def initialize
    raise Error
  end

  def to_s
    raise
  end

  def inspect
    to_s
  end
end

Baz.new
```

Command
```
exe/rdbg -e 'catch Baz::Error ;; c ;; up ;; i' -e c target.rb
```

I expect the frame information to be shown, but instead my original exception is raised again and the debugger exits.

I'm really not sure what the best solution is here. Rescue then display `rescued SomeException when inspecting`?  Or perhaps `debug` can have it's own object here that's used in it's place?

The patch below solves the issue.

```diff
diff --git a/lib/debug/thread_client.rb b/lib/debug/thread_client.rb
index 16cd2b7..808341b 100644
--- a/lib/debug/thread_client.rb
+++ b/lib/debug/thread_client.rb
@@ -29,6 +29,8 @@ module DEBUGGER__
       else
         obj.pretty_inspect
       end
+    rescue => ex
+      colored_inspect("(rescued #{ex.inspect} during inspection)")
     end
 
     def colorize_cyan(str)
```

**Comment by st0012** [comment]
I think your patch should work but maybe we can fallback to `#to_s` if possible? like

```ruby
rescue => ex
  err_msg = "(rescued #{ex.inspect} during inspection)"
  string_result = obj.to_s rescue nil

  # don't colorize the string here because it's not from user's application
  # this could also help spot the special condition
  if string_result
    "#{string_result} #{err_msg}"
  else
     err_msg
  end
end
```

**Comment by adam12** [comment]
Looks good to me. I'll submit a PR.

**Comment by ko1** [comment]
I'm not sure to fallback with "to_s".
the purpose of "inspect" is to use in debug and so on, but "to_s" is not (for example, it can generate long string).

**Comment by st0012** [comment]
@ko1 isn't `inspect` generally generates a longer string than `to_s`? for example:
<img width="1354" alt="截圖 2021-05-31 上午11 43 51" src="https://user-images.githubusercontent.com/5079556/120136765-79dbb900-c205-11eb-89c5-24f1d5648729.png">

I think in this kind of special cases, we should provide as much information to users as possible. by falling back to `to_s`, at least the user can know what instance the object is.

**Comment by ko1** [comment]
I agree on "at least the user can know what instance the object is.".

For example, `String#to_s` removes the quote and it will introduce confusion. In general, they shouldn't raise an error.

It's a corner case, I propose: to show the error and the class. Or write an error (and the class) and show `to_s` output with `to_s result: ` or something explicitly.

If user wants to get "to_s" result, they can use `p obj.to_s`.

**Comment by ko1** [comment]
> for which I was debugging

I understand the motivation (I missed this line)

**Comment by adam12** [comment]
Are we thinking something like

```ruby
"(rescued #{ex.class} while inspecting #{obj.class})"
```

I don't have an overall preference, and I'm surprised `URI` raised an exception for `inspect`, so I'll try to submit an issue there once I can reproduce it, but for now I'd expect `debug` to handle this gracefully.

**Comment by ko1** [comment]
I found that when I got an error from `inspect` I want to debug it, so I want to get an backtrace output.
It depends on the development stage:

1. If I'm writing a `inspect` method, the bug is due to myself and I want to debug it.
2. If the object is from library, sometimes I want to ignore it, but sometimes I want to know the error.

(not concluded)

**Comment by st0012** [comment]
@ko1 how about updating the message with `"#{string_result}" from #to_s because of #{err_msg}"` to make it more explicit.

@adam12 do you think injecting the backtrace (maybe just the first 20 lines) would help you debug the issue?

**Comment by adam12** [comment]
> do you think injecting the backtrace (maybe just the first 20 lines) to the message would help you debug the issue?

Hard to say. In this specific instance, I didn't care about `URI#inspect` and wasn't debugging it, but because I had an invalid `URI` object assigned to a local, it was crashing when debugging with `info` inside the frame of my own application I was interested in.

So I would have been happy with just knowing that `URI#inspect` crashed during inspection, so I could continue debugging my other issue.

Eventually I would have wanted to look at the reason `URI#inspect` was crashing. At that point in time, I should be able to treat it as any other error, regardless if it occurred inside the `inspect` method.

Hope this helps?

**Comment by st0012** [comment]
@adam12 thanks for the input 👍 I think at this stage we can just modify the message a bit like I mentioned above, and revisit this in the future if needed.

**Comment by ko1** [comment]
I'm not familiar with `pp` (or `p`), it should be a problem to see exception in nested data like that:

```ruby
class C
  def initialize
     @important_a = ...
     @important_b = ...
     @not_important_c = inspect broken object
...
```

In this case, it will helpful to show all data without `@not_important_c`.
Not high-priority.

**Comment by adam12** [comment]
I've updated #47 with new messaging, screenshot, and test.
