### ISSUE TITLE
undefined method `start_with?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by st0012** [ruby/debug#466]
**Your environment**

* `ruby -v`: `3.0.3`
* `rdbg -v`: `1.3.x`, `1.4.0`, current master (`dd56fb84b53d96878e2d666bb704422dec28787d`)

**Describe the bug**

`CallTracer#skip?` can sometimes cause `NoMethodError` in my app.

```
/Users/st0012/projects/debug/lib/debug/tracer.rb:23:in `skip?': undefined method `start_with?' for nil:NilClass (NoMethodError)
```

The problematic tp event looks like this:

```
irb(CallTracer (enabled)):022:0> [tp.event, tp.callee_id, tp.self, tp.path, tp.lineno]
=> [:c_call, :each, #<Enumerator::Lazy: ...>, nil, 0]
```

**To Reproduce**

**Can't reproduce atm.**

I tried simulating the same setup but it works:

```rb
binding.b(do: "trace call")

def foo(i)
  puts(i)
end

[1,2,3].lazy.each do |i|
  foo(i)
end
```

```
DEBUGGER (trace/call) #th:1 #depth:2 > Enumerable#lazy at target.rb:32
DEBUGGER (trace/call) #th:1 #depth:2 < Enumerable#lazy #=> #<Enumerator::Lazy: [1, 2, 3]> at target.rb:32
DEBUGGER (trace/call) #th:1 #depth:2 > Enumerator#each at target.rb:32
DEBUGGER (trace/call) #th:1 #depth:3 >  Array#each at target.rb:32
DEBUGGER (trace/call) #th:1 #depth:4 >    block at target.rb:32
DEBUGGER (trace/call) #th:1 #depth:5 >     Object#foo at target.rb:28
DEBUGGER (trace/call) #th:1 #depth:6 >     Kernel#puts at target.rb:29

....
```

**Expected behavior**

Tracer shouldn't cause the issue.

**Additional context**

I can easily avoid the issue by patching `tp.path&.start_with?`. But I want to first check if `c_call` tps can have `nil` path.

**Comment by ko1** [comment]
Sorry I missed this issue.

Yes, `path` can be nil.

**Comment by ko1** [comment]
Note that if you can repro the situation, `caller` methods will help to understand the situation.

```ruby
pp caller unless tp.path
```

**Comment by st0012** [comment]
Thanks for the fix.
