### ISSUE TITLE
Chrome fails to navigate to Chrome DevTools page once in a while

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#474]
**Your environment**

* `ruby -v`: 
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
* `rdbg -v`:

**Describe the bug**
Chrome doesn't navigate to Chrome DevTools page like below:

![Screen Shot 2022-01-02 at 11 13 47 AM](https://user-images.githubusercontent.com/59436572/147864328-786ae25f-26a9-4bd4-b592-511dc76358e6.png)

**To Reproduce**
It's hard to reproduce it, but this bug tends to be happened when Chrome debugging is used first.

**Expected behavior**
It should navigate to Chrome DevTools page.

**Additional context**

**Comment by st0012** [comment]
Oh I've experienced this problem too! I thought it's because of my environment.
