### ISSUE TITLE
Is it possible to support callstack navigation like pry?

### ISSUE THREAD

**Issue by jrochkind** [ruby/debug#483]
Pry has:

* up: Moves the stack frame up. Takes an optional numeric argument to move multiple frames.
* down: Moves the stack frame down. Takes an optional numeric argument to move multiple frames.
* frame <n>: Moves to a specific frame. Called without arguments displays the current frame.

One thing some people miss moving on from pry.  Would it be feasible to implement here?

**Comment by st0012** [comment]
They're [already implemented](https://github.com/ruby/debug#frame-control) 🙂 

```

* `f[rame]`
  * Show the current frame.
* `f[rame] <framenum>`
  * Specify a current frame. Evaluation are run on specified frame.
* `up`
  * Specify the upper frame.
* `down`
  * Specify the lower frame.
```

**Comment by ko1** [comment]
* do you say about pry-debug?
* do you use `up <num>` ?

**Comment by ko1** [comment]
(`up/down <num>` is reasonable to introduce it. The last question is just curious)

**Comment by jrochkind** [comment]
Oh great, thank you, sorry!  I do not personally use `up <num>` very often! Closing this, sorry!
