### ISSUE TITLE
Puma takes a really long time to quit when debug gem is loaded

### ISSUE THREAD

**Issue by Mathieuu** [ruby/debug#485]
On the puma repo, I was told to post the issue here. I am not sure which gem needs a fix though:

See https://github.com/puma/puma/issues/2796

**Describe the bug**

Puma application takes 20 seconds to quit when it has two workers configured with fork_worker and the [debug](https://github.com/ruby/debug) gem is loaded.

**Puma config:**

Please copy-paste your Puma config AND your command line options here.

**To Reproduce**

See that repo: https://github.com/Mathieuu/DebugPuma

I scaffold a rails app with `rails new app --api` and [did the following changes](https://github.com/Mathieuu/DebugPuma/commit/ce918532536f062d1ebfa0efc82a94e44f257cd4).

Launch the server with `rails s` then press ctrl+c to exit the process. It hangs for 20 seconds.
Remove `debug` from the gemfile or `fork_worker` from `config/puma.rb` and it exits instantly.

**Comment by st0012** [comment]
I haven't get to the bottom of it, but it's because the local console UI hangs for its `waitpid` call in the `at_exit` block.

https://github.com/ruby/debug/blob/bbc58316a7195b11e5ec3eeb5dd89e6114208402/lib/debug/local.rb#L101

**Comment by ko1** [comment]
https://github.com/ruby/debug/pull/489 may fix it.
