### ISSUE TITLE
`rails s` on vscode doesn't work

### ISSUE THREAD

**Issue by ko1** [ruby/debug#501]
**Your environment**

* `ruby -v`: 3.1
* `rdbg -v`: 1.4

**Describe the bug**

On vscode, running `rails s` with debugger doesn't work because it tries to connect to VScode twice. It should use same connection.
Maybe it is same for remote debugging session.

**Comment by st0012** [comment]
Do you mean seeing error message in vscode like: `connect ENOENT /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/ruby-debug-sock-501/ruby-debug-st0012-37797`?

**Comment by ko1** [comment]
like that:

```
ko1@WSL2 ~/src/rb/ruby-debug/app/tapp
$ rdbg --command --open --stop-at-load --sock-path=/tmp/ruby-debug-sock-1000/ruby-debug-ko1-16486 -- bundle exec rails s
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-1000/ruby-debug-ko1-16486)
DEBUGGER: Connected.
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-1000/ruby-debug-ko1-16486)
DEBUGGER: wait for debugger connection...
```

**Comment by ko1** [comment]
I understand:

1. `rails s` (Process 1) accepts the debugger's connection.
2. 1 kicks `bin/rails s` (Process 2) and this process also try top accepts the debugger connection. Howver,
3. Process 1 terminates and debugger connection from VSCode is closed. Howver, Process 2 waits VSCode connection.

Now I have no good solution about non-fork type multi-process mode.
Execute `bin/rails s` doesn't have an issue, so now we need to use it.

I close this ticket and please reopen if someone has a good solution.

**Comment by ko1** [comment]
`bundle exec` also has this issue, but `bundle exec` is cared specially in session.rb to ignore `exec` case.
