### ISSUE TITLE
Terminated Event is not fired before disconnect

### ISSUE THREAD

**Issue by oats4goats** [ruby/debug#523]
**Your environment**

* `ruby -v`: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
* `rdbg -v`: rdbg 1.4.0

**Describe the bug**
It looks like in Remote Debug mode (DAP client `nvim-dap`) after the last program step, the debugger disconnects but doesn't fire 'Terminated Event'. In such situation, DAP client doesn't know the [debugging of the debuggee has terminated](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated) and keeps the debug session alive forever. Thus requiring manual treatment.

**To Reproduce**
1. Start a debugger with `rdbg --open --port 38698 target.rb` in a terminal
2. Attach to the adapter with `nvim-dap`
3. Continue or step over till the very end of the program.
4. The debugger in the terminal disconnects.

Example of console output:
```
#14867:[>] {"type":"request","seq":52,"arguments":{"granularity":"statement","threadId":1},"command":"next"}
#14867:[<] {"type":"response","command":"next","request_seq":52,"success":true,"message":"Success","seq":62}
12
DEBUGGER: Disconnected.
```

**Expected behavior**
Before the debugger disconnects 'Terminated Event' is issued so the client could close the debug session properly.

**Additional context**
Relevant discussion in [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap/issues/429)

**Comment by ko1** [comment]
https://github.com/mfussenegger/nvim-dap/pull/436 solves the issue?

It's a bit tough to observe the debuggee's liveness (because the debugger runs in same process).
But not impossible.

If it should be supported, I'll work it.

**Comment by mfussenegger** [comment]
The discussion in https://github.com/mfussenegger/nvim-dap/issues/469 and the change that resulted out of the conversion (https://github.com/mfussenegger/nvim-dap/pull/481) may be relevant to this as well.

The TL;DR version is that if the debugger process runs to completion, the debug adapter *must* send a terminated event. If the client sends a disconnect request before the debugger process finishes, the debug adapters behavior depends on whether a launch/attach configuration was used and on the (optional) `terminateDebugee` flag of the request.

**Comment by ko1** [comment]
> the debug adapter must send a terminated event.

Could you give me a reference?

**Comment by st0012** [comment]
I think he refers to the `Debug session end` part of https://microsoft.github.io/debug-adapter-protocol/overview?

**Comment by ko1** [comment]
Thank you.

> In all situations where a debug adapter wants to end the debug session, a [terminated](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated) event must be fired.

I agree it should be, but not sure when the connection was lost accidentally.
