### ISSUE TITLE
opening vscode fails on windows

### ISSUE THREAD

**Issue by sevenc-nanashi** [ruby/debug#541]
**Your environment**

* `ruby -v`: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [i386-mingw32]
* `rdbg -v`: rdbg 1.4.0

**Describe the bug**
When I try to open debugger on vscode, it fails:
```
discorb on  migrate/api-v10 [$] via  via  v3.0.3 
❯ rdbg --open=vscode .\__gi_dtest.rb
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/config.rb:384:in `check_dir_authority': C:/Users/MyUserName/AppData/Local/Temp/ruby-debug-sock-0's mode is 40755 (should be 040700) (RuntimeError)
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/config.rb:401:in `unix_domain_socket_tmpdir'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/config.rb:421:in `unix_domain_socket_dir'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/server.rb:406:in `initialize'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/session.rb:1935:in `new'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/session.rb:1935:in `open_unix'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/session.rb:1911:in `open'
        from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/open.rb:13:in `<top (required)>'
        from <internal:C:/develop/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/develop/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

**To Reproduce**
Run `rdbg --open=vscode some.rb`

**Expected behavior**
It opens vscode.

**Additional context**

**Comment by jabamaus** [comment]
I'm stuck on this too. I'd love to be able to try the debugger with vscode on windows. Is it a bug or user error? Anyone shed any light on this?

**Comment by dsisnero** [comment]
Same as #506 Use port

`rdbg --open=vscode --port 12345`

use launch.json with port

```
"type": "rdbg",
"name": "Attach with rdbg",
"request": "attach",
"port": 12345
```

**Comment by ruehsn** [comment]
I've updated my launch.json config to:

```

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "rdbg",
            "name": "Debug current file with rdbg",
            "request": "launch",
            "script": "${file}",
            "args": [],
            "askParameters": true,
            "debugPort": "12345"
        },
        {
            "type": "rdbg",
            "name": "Attach with rdbg",
            "request": "attach",
            "debugPort": "12345"
        }
    ]
}
```
but then get this error message: connect ECONNREFUSED 127.0.0.1:12345
image

I think I missed a step...

**Comment by ko1** [comment]
`rdbg --open=vscode` generate its own launch.json in tempfile, so your launch.json is ignored.

There are two ways:

1. Use existing launch.json if `.vscode/launch.json` exists.
2. Generate with `debugPort`.

1 is easy so I'll try it.

**Comment by ko1** [comment]
Ah, 1 is not possible because we need to add special configuration parameter for auto launch and auto attach.
I'll try 2 on next and next version.

**Comment by ruehsn** [comment]
Thanks for the quick reply! So it's not possible to launch use the `rdbg --open=vscode` command in Windows at this time.  Is it possible to start VS Code normally and debug ruby files that way?  I'm struggling to make that work as well... should I open a new issue or continue that conversation on https://github.com/ruby/vscode-rdbg/issues/18  ?
Thanks

**Comment by ko1** [comment]
> Is it possible to start VS Code normally and debug ruby files that way?

Yes, with next release of vscode-rbdg.

**Comment by ko1** [comment]
Ah, I could fix it.
9342694faaa4deb3f3bc89cbd407b7e869369110
