### ISSUE TITLE
Reproduce behavior of running "sleep" in byebug.

### ISSUE THREAD

**Issue by bjonnh-work** [ruby/debug#549]
**Your proposal**
We have Selenium/Capybara test for our Rails application. What we used to do with byebug is call the debugger and run `sleep <some number>`. This would allow us to continue using the app in the selenium VNC to work on the current state of the page at that time. We couldn't find a way to reproduce that behavior with debugger.

**Additional context**
Of course we could put sleeps in the code, but that would require us to know beforehand that we want to manipulate the page manually.

**Comment by ko1** [comment]
Sorry I couldn't understand what is required and what `byebug` does. For example, we can call `eval sleep N` on debugger's prompt. Do you want to run another threads? (and now debug.gem doesn't support it).

**Comment by bjonnh-work** [comment]
If I have a selenium spec and I put `byebug` in my code somewhere in it.
And run `sleep 300` in byebug. I can use the Rails app, so I suppose byebug restarts the threads when it runs a  command?

If I do the same thing with `debugger` with `eval sleep 300`, the Rails application still has its thread stopped so it doesn't reply to queries.

**Comment by ko1** [comment]
Yes, byebug doesn't stop other threads.
debug.gem stops all threads while the prompt is shown.

So maybe my question was your request:

> Do you want to run another threads? (and now debug.gem doesn't support it).

**Comment by bjonnh-work** [comment]
That's what I guessed. We'll wait for that to be supported then. Thanks!
