### ISSUE TITLE
VSCode Breakpoints not being deleted on Windows

### ISSUE THREAD

**Issue by golirev** [ruby/debug#588]
**Your environment**

* `ruby -v`:  ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
* `rdbg -v`: rdbg 1.4.0

```
tsuyoshi@TPE14 UCRT64 ~/work/ruby/debug
$ git log --oneline
0a25691 (HEAD -> master, origin/master, origin/HEAD) Update both servers' evaluate logic
```

**Describe the bug**

VSCode Breakepoints can be added. But it can not be deleted.
When you press a Breakepoint mark, the Breakepoint mark disappears, but the execution still stops there.

**To Reproduce**

**Expected behavior**

When you press the Breakpoint mark, the Breakpoint mark disappears and the execution does not stop there anymore.

**Additional context**

I think this issue comes from the difference in the path delimiters of the two paths to compare.
I think the following correction will fix this.

```
diff --git a/lib/debug/session.rb b/lib/debug/session.rb
index eb2b224..378944f 100644
--- a/lib/debug/session.rb
+++ b/lib/debug/session.rb
@@ -1370,6 +1370,7 @@ module DEBUGGER__
     end

     def clear_line_breakpoints file
+      file = resolve_path(file)
       @bps.delete_if do |k, bp|
         if (Array === k) && DEBUGGER__.compare_path(k.first, file)
           bp.delete
```

**Comment by ko1** [comment]
Thank you. I'll apply it.

NOTE:
VSCode sends "c:\\ko1\\t.rb` and Ruby's iseq stores normalized path like `c:/ko1/t.rb` so it doesn't match. It is solved by `resolve_path()`
