### ISSUE TITLE
Label breakpoint output

### ISSUE THREAD

**Issue by st0012** [ruby/debug#59]
I've been playing breakpoints for a while. And one thing that bothers me is that it's not always easy to find the breakpoint messages. Because they are usually surrounded by debugger's prompts or other output:

**Current BP messages**

<img width="398" alt="before bp label" src="https://user-images.githubusercontent.com/5079556/120581826-0e405880-c45e-11eb-9ffc-6d85ec1d9f11.png">

But colorizing them like backtrace or frame info may just cause more confusion. 

So instead, I want to use reverse coloring effect to add something called "breakpoint label", which looks like this:

**Proposed messages**

<img width="390" alt="after bp label" src="https://user-images.githubusercontent.com/5079556/120581843-15676680-c45e-11eb-891d-0d6ad618f1ad.png">

It also looks great with a bright background.

<img width="287" alt="截圖 2021-06-03 上午11 29 08" src="https://user-images.githubusercontent.com/5079556/120582341-eac9dd80-c45e-11eb-93cb-ae649e5ffe74.png">

### Notes

- This will be applied to the content of `Breakpoint#to_s`.
- I also plan to colorize some breakpoint (like watch breakpoint)'s value. The color scheme will be the same as backtrace.
  - It's also possible to use colored inspect on changed values, but I'm not sure if that'd be an overkill or be too noisy? @ko1 wdyt?

**Comment by ko1** [comment]
Let's try!

BTW `BP` is of course "Break Point". Is it readable?

**Comment by st0012** [comment]
I use `BP` because the current output uses `bp`, but I don't think that's clear to users. 

To me, `BP` implies there are 2 words "Break Point", which is not how we usually spell `breakpoint`. However just calling it `B` is more confusing.

So if it's ok to you, I prefer using `Breakpoint`. The lines aren't long in general, so I don't think the extra characters would could issues.

**Comment by st0012** [comment]
I think I'm wrong here. `Breakpoint` doesn't make the line too long but is verbose.

<img width="479" alt="截圖 2021-06-03 下午5 45 51" src="https://user-images.githubusercontent.com/5079556/120624713-8bd28b80-c493-11eb-9760-b2fdbf624e7a.png">

I'll use `BP` for now and change it later if others have different opinions.

**Comment by ko1** [comment]
How about `#0 Breakpoint: <color>Watch</color>` ?

**Comment by st0012** [comment]
> How about `#0 Breakpoint: <color>Watch</color>` ?

Result:

<img width="343" alt="截圖 2021-06-03 下午10 20 26" src="https://user-images.githubusercontent.com/5079556/120660431-e7177480-c4b9-11eb-93cf-d509ddce5115.png">

I feel like the breakpoint indication should also be included in the label. Otherwise I still need to read the white characters to see what the message is for. 

I still prefer the originally proposed style 🤔

**Comment by ko1** [comment]
Ok, let's use original one.
