### ISSUE TITLE
Quick exit command

### ISSUE THREAD

**Issue by st0012** [ruby/debug#6]
Currently, all exit/quit/kill commands require an additional confirmation step.

https://github.com/ruby/debug/blob/4a3046ba87f573f2c21cce590bce206e469dba76/lib/debug/session.rb#L236-L251

```
❯ rdbg foo.rb
[1, 2] in foo.rb
=>    1| a = 1
      2| puts(a)
--> #0  foo.rb:1:in `<main>'

(rdbg) exit
Really quit? [Y/n] Y
```

```
❯ rdbg foo.rb
[1, 2] in foo.rb
=>    1| a = 1
      2| puts(a)
--> #0  foo.rb:1:in `<main>'

(rdbg) quit!
Really kill? [Y/n] Y
```

 Without changing any existing commands, I wonder if it's ok to add the `exit!` command? It'll allow users to quickly exit the current session without hitting `Y` to confirm it.

```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1

(rdbg) exit!
```

**Comment by ko1** [comment]
I understand the motivation.

The problem is, Ruby has `exit!` method which terminates process immediately without care about `ensure` clauses. It is confusing.

**Comment by st0012** [comment]
I see. How about changing `quit!` then? So the command would be

- `quit`, `q` - quit with confirmation
- `quit!`, `q!` - quit immediately
- `kill` - kill the process with confirmation
- `kill!` - kill the process immediately

**Comment by ko1** [comment]
I see. It is one idea. No `exit(!)` is clear (no confusion). Could you make a patch?

**Comment by st0012** [comment]
Of course 👍
