### ISSUE TITLE
Warnings: Detaching after fork from parent process

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [ruby/debug#601]
**Your proposal**
These warnings are noisy in test output.

```
DEBUGGER: Detaching after fork from parent process 17625
DEBUGGER: Attaching after process 17625 fork to child process 17658
```

Maybe they should instead be info level, to make it possible to ignore them without ignoring other warnings.

Or remove them entirely?

**Comment by ko1** [comment]
https://github.com/ruby/debug/issues/394
