### ISSUE TITLE
Output is garbled

### ISSUE THREAD

**Issue by WillTaylor22** [ruby/debug#603]
**Your environment**

* `ruby -v`: 2.7.5p203
* `debug`: 1.4.0
* rails 7.0.2.3
PLATFORMS:  x86_64-darwin-21
MacBook Pro Monterey 12.0.1

**Describe the bug**

In Terminal, when I break, I always get a garbled output.

Here is what happens when I type 1 + 1 and hit enter:
16:26:00 web.1  | (rdbg) (rdbg) 1    # ruby(rdbg) 1     # ruby(rdbg) 1 +    # ruby(rdbg) 1 +     # ruby(rdbg) 1 + 1    # ruby  2

**To Reproduce**

**Expected behavior**
It should work like irb.

**Comment by ko1** [comment]
Could you describe more to reproduce?

**Comment by WillTaylor22** [comment]
May be a foreman issue.

Created a fresh rails app, added a new route & action and immediately called debugger.

I then added a few things around how I'm running the server in my main app:

I have a file ./bin/dev containing:
#!/usr/bin/env bash
foreman start -f Procfile.dev "$@"

Make this executable with `sudo chmod u+x ./bin/dev`

And a file Procfile.dev containing:
`web: bin/rails server -p 3000`

When I run Procfile.dev, I get the error above with the garbled debugger.
When I run bin/rails server -p 3000 on its own, the debugger is fine.

No worries if this isn't one you can help with, given that it seems to be caused by Foreman.

**Comment by ko1** [comment]
I need to understand foreman's TTY.
I heard another issue on foreman so I need to check it.

**Comment by atstockland** [comment]
Sorry I don't have anything to add or assist.  But, my debug output is unreadable also.  There's no command line to interact with---it's just blank at the end of the break output.  I can attempt to type method names or variables in there, but the output of that is buried in so much junk it takes me 10 minutes to find where the variable output was printed.  Happened as soon as I switched over from Pry to Debug.  Rails 7, iterm, MacOS, zsh.

**Comment by jschuman** [comment]
I am experiencing this as well.  Was this issue closed as just a recommendation to setup remote debugging?
