### ISSUE TITLE
Weird behavior on catch command

### ISSUE THREAD

**Issue by st0012** [ruby/debug#609]
**Your environment**

* `ruby -v`: `ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]`
* `rdbg -v`: `1.5.0`

### Description

I spotted a weird behavior when using `catch Exception` or `catch StandardError` and then causing an exception in the console. Example:

```
❯ exe/rdbg -e "catch Exception do: 'debugger spotted an error' ;; raise 'foo' ;; " target.rb
[1, 1] in target.rb
=>   1| puts(123)
=>#0    <main> at target.rb:1
(rdbg:commands) catch Exception do: 'debugger spotted an error'
#0  BP - Catch  "Exception"
(rdbg:commands) raise 'foo'
[1, 1] in (rdbg)/target.rb
=>   1| raise 'foo'
=>#0    <main> at (rdbg)/target.rb:1
  #1    [C] Binding#eval at ~/projects/debug/lib/debug/thread_client.rb:369
  # and 2 frames (use `bt' command for all frames)

Stop by #0  BP - Catch  "Exception"
(rdbg:catch) 'debugger spotted an error'
"debugger spotted an error"
eval error: foo
  (rdbg)/target.rb:1:in `<main>'
nil

# catch breakpoint is triggered and performed command as expected, so far so good.
# let's run some other commands
(rdbg) ls    # outline command
Object.methods: inspect  to_s

# for some reason, the catch bp's command is triggered again
(rdbg:catch) 'debugger spotted an error'
"debugger spotted an error"

# and it exits the current bp for no apparent reason
123
```

### Reproduction

**Scripit**

```rb
puts(123)
```

**Command and output**

1. `$ exe/rdbg -e "catch Exception do: 'debugger spotted an error' ;; raise 'foo' ;; " target.rb`
2. Run arbitrary debugger command, like `ls`

### Expected Behavior

1. The `'debugger spotted an error'` message is only printed once.
2. The arbitrary command doesn't exit the debugging session.

### Actual Behavior

1. The `do:` command is executed for the second time when no new exception is raised.
2. When 1 happens, it also tries to leave the current debugging session without being told to do so.

However, if we use a more specific exception name, like `catch RuntimeError`, neither the problem occurs.

Therefore, I suspect that debugger has some internal exceptions happening between step 1 and 2, which triggered the catch breakpoint unexpectedly.

**Comment by st0012** [comment]
Yeah there is an exception raised from `reline` that triggered the breakpoint:

```
irb( BP - Catch  "StandardError"):003:0> exc.backtrace
=>
["/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/config.rb:144:in `readlines'",
 "/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/config.rb:144:in `read'",
 "/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:314:in `inner_readline'",
 "/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:254:in `readmultiline'",
 "/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'",
 "/Users/st0012/projects/debug/lib/debug/console.rb:122:in `block in readline'",
 "/Users/st0012/projects/debug/lib/debug/console.rb:103:in `readline_setup'",
 "/Users/st0012/projects/debug/lib/debug/console.rb:121:in `readline'",
 "/Users/st0012/projects/debug/lib/debug/local.rb:72:in `block in readline'",
 "/Users/st0012/projects/debug/lib/debug/local.rb:84:in `block in setup_interrupt'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:1742:in `intercept_trap_sigint'",
 "/Users/st0012/projects/debug/lib/debug/local.rb:77:in `setup_interrupt'",
 "/Users/st0012/projects/debug/lib/debug/local.rb:71:in `readline'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:370:in `wait_command'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:330:in `block in wait_command_loop'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:329:in `loop'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:329:in `wait_command_loop'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:286:in `process_event'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:194:in `session_server_main'",
 "/Users/st0012/projects/debug/lib/debug/session.rb:164:in `block in activate'"]
```

It's [`Errno::ENOENT` raised by `File.readline`](https://github.com/ruby/reline/blob/9ab5850444b49aff8e360a84eb1dfa425e96ced1/lib/reline/config.rb#L144).

**Comment by st0012** [comment]
@ko1 I think the straightforward solution is to mark `reline`'s code as internal in the `skip_internal_path?` method. Which should look like this? `path.match?(/lib\/reline[\/\.]/)`. 

The drawback would be that developers working with `reline` won't be able to catch the errors it raises. But I think it's worth the tradeoff to make `catch Exception` or `catch StandardError` work. Because users don't always know what's the exception that changes their application's behavior (raised and rescued). I personally use the later very often.

Of course, the ideal solution would be something like:

```rb
# console.rb
  def readline prompt
    readline_setup prompt do
      DEBUGGER__.skip_breakpoint do
        Reline.readmultiline(prompt, true){ true }
      end
    end
  end
```

But I can't come up with an implementation that doesn't need to use a global state for that, which I think would be thread/ractor unsafe?

**Comment by ko1** [comment]
on 1.5.0 only? (not on 1.4.0?)

**Comment by ko1** [comment]
repro on 1.4.0.

**Comment by st0012** [comment]
Yeah I think it's been there for a while, not something new.
