### ISSUE TITLE
bv command

### ISSUE THREAD

**Issue by kaiquekandykoga** [ruby/debug#610]
What is the purpose of bv command?

I have not found any documentation about it, so it looks a hidden command.

Perhaps adding a documentation for it would make sense.

https://github.com/ruby/debug/blob/5d16d8731e85ae7ef20440d7c8e12fa83bef1995/lib/debug/session.rb#L532-L556

**Comment by ko1** [comment]
It's not implemented yet so no documented.

**Comment by ko1** [comment]
all right, I remove this feature to reduce confusion.

**Comment by ko1** [comment]
https://github.com/ruby/debug/pull/612

**Comment by kaiquekandykoga** [comment]
Thank you @ko1 .

I was not trying to give you more work to do. You could have let the code there.
