### ISSUE TITLE
Pressing <Enter> with blank prompt should run last entered command

### ISSUE THREAD

**Issue by aaronbrethorst** [ruby/debug#617]
**Your proposal**

Previously with `byebug`, when I was debugging my code and stopped at a breakpoint, I could single-step through the code like this:

```
n <enter>
<enter>
<enter>
<enter>
```

And so on. Pressing the enter key without any other input at the prompt would re-run the last command.

It does not appear that this is supported with the `debug` gem, at least not out of the box.

**Comment by adam12** [comment]
This behaviour is supported and works for me (1.5.0). What are you seeing that indicates it not working?

What happens if you simulate something simple, like `bt` or `info`?

```
$ rdbg -c irb
info <enter>
<enter>
```

**Comment by aaronbrethorst** [comment]
Interesting, the example you provide above (`rdbg -c irb`) works perfectly for me too. And then when I went to provide you with a more concrete example from debugging an RSpec spec, that started working, too. Weird, but I'm glad it's working now. Thanks for your time!
