### ISSUE TITLE
DAP Server stack trace should use startFrame and levels parameters 

### ISSUE THREAD

**Issue by dpeacock** [ruby/debug#637]
**Your environment**
* `ruby -v`: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
* `rdbg -v`: rdbg 1.5.0

**Describe the bug**
The DAP server does not use the parameters on the [StackTrace](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StackTrace) request.  In some instances this can result in a very large stack trace being returned, which can take extra time.  VS code for example requests a depth of 20 at a time and has a 'more' button to retrieve additional data.  Currently these are ignored, and the more button just resends the same data every time.

**To Reproduce**
Set a breakpoint in VS Code where the stack depth is > 20.  VS Code will request 20 levels, but the dap server will ignore this and send the entire stack trace.

**Expected behavior**
Only send the requested levels.

**Comment by ko1** [comment]
Thank you, I don't know this behavior.

**Comment by ko1** [comment]
I understand `levels` is information how many levels are needed (20 frames for example).
What happens on "more" button is pushed?
StackTrace event with 40 levels?
StackTrace event with more 20 levels? (but I can't find the start level).

**Comment by ko1** [comment]
memo;

```ruby
def rec0
  a = 0
end

(1..1000).each{|i|
  eval("def rec#{i} = (a = #{i}; rec#{i-1})\n")
}

rec1000```
