### ISSUE TITLE
[Document Request] Add a migration guide for byebug users

### ISSUE THREAD

**Issue by st0012** [ruby/debug#644]
## What 

1. Add a document `docs/migrate_from_byebug.md` as the migration guide for byebug users.
2. Add a link to it in the readme

### Content

- It should list command comparisons, especially around step debugging, to help users learn what's changed or not changed.
  - Preferably using markdown table for this instead of a separate page to optimize reader's experience.
- It should also emphasize the features that're unique to the debugger as an attraction.

## Why

Based on [the latest Rails community survey](https://rails-hosting.com/2022/#what-is-your-go-to-ruby-debugger-tool), `byebug` has 30% of the market share vs debugger's 10%. Given that `byebug` and the debugger share the same user base, a migration guide should help speed up the adoption.

![Screenshot 2022-05-25 at 14 56 46](https://user-images.githubusercontent.com/5079556/170279772-5d1f484c-2712-441c-9e59-442fd0a061de.png)

**Additional context**

- I know there's already a [debug command comparison sheet](https://docs.google.com/spreadsheets/d/1TlmmUDsvwK4sSIyoMv-io52BUUz__R5wpu-ComXlsw0/edit#gid=0). It'll be a nice supporting material but it's not specific for byebug. So I think it can't replace the migration guide I mentioned above.
- If there's no objection on this idea, I'll work on it.

**Comment by st0012** [comment]
I've written [this post](https://st0012.dev/from-byebug-to-ruby-debug) as suggested 😄 
It also mentions a few points on "why users should **not** migrate". But I think the migration should be beneficial in general.

**Comment by ko1** [comment]
Thank you, could you give me a PR to merge this link in README?
