### ISSUE TITLE
Regression from 1.5.0 to master performing 'next' command with multiple waiting threads

### ISSUE THREAD

**Issue by rockorequin** [ruby/debug#646]
**Your environment**

* `ruby -v`: 
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

* `rdbg -v`:
rdbg 1.5.0 (master git)

**Describe the bug**
I am experiencing a regression from 1.4.0 to git master, where when I'm in debugging my Rails app, debug 1.4.0 can perform the 'next' command correctly, ie stepping to the next line, but debug git master performs a 'mini-continue', ie it stops many lines later.

I think the cause of the regression is the code change in session.rb#restart_all_threads in the line "request_tc :continue":

```
      waiting_thread_clients.each{|tc|
        next if @tc == tc
        request_tc :continue
      }
```

request_tc adds the :continue command to @tc, whereas in 1.4 it added it to the local tc variable. This is significant in my case because there are three waiting threads.

So I think the code should be the same as before:

```
      waiting_thread_clients.each{|tc|
        next if @tc == tc
        tc << :continue
      }
```

This change fixes the issue in my Rails app.

**To Reproduce**
I can reproduce this in my Rails app but I can't post any code, sorry.

**Comment by st0012** [comment]
Yeah that's a mistake on my part, sorry. I'll push a PR shortly.

**Comment by st0012** [comment]
I assume you're using the master branch though? Because that change wasn't in the `1.5.0` release.

**Comment by rockorequin** [comment]
> I assume you're using the master branch though? Because that change wasn't in the 1.5.0 release.

Yes, I'm on master. Sorry, I could have made that clearer! I cloned master because I ran into the extremely slow bt command problem when safe inspecting very large variables and wanted to patch the gem locally.

**Comment by rockorequin** [comment]
I can confirm that 1.5.0 doesn't have the problem, I must have had a cached version running. It's only in master.
