### ISSUE TITLE
paste is pasting extra characters

### ISSUE THREAD

**Issue by kikonen** [ruby/debug#649]
**Your environment**

* `ruby -v`: 
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]

* `rdbg -v`:
rdbg 1.5.0

**Describe the bug**

When pasting something into debug console, extra characters are inserted

For example, pasted "break" and "^[[200~" and "^[[201~" is always pasted also in
```
(ruby:remote) ^[[200~break^[[201~
````

**To Reproduce**

1) puma server running in docker container
** require 'debug/open_nonstop'
2) rdbg --attach
3) Paste something in debugger console

**Expected behavior**

- paste won't paste extra characters
- no_color turns off all colors
- no redundant and useless '(rdbg:remote) c    # continue command" or such shown when trying to enter commands, it just makes usage irritating due to flashing  '# whatever useless text'
- 

**Additional context**

config I used
```
config set nonstop true
config set no_color true
config set use_short_path true
```

**Comment by znz** [comment]
I think "^[[200~" and "^[[201~" are [Bracketed-paste](https://en.wikipedia.org/wiki/Bracketed-paste).
Terminal application's setting perhaps can disable it.

**Comment by kikonen** [comment]
Have to check if there is some setting. Strangely this is only case were I have seen such happening.

**Comment by ko1** [comment]
debug.gem uses Reline which is used by irb for console.
irb doesn't show this issue?

**Comment by ko1** [comment]
Please reopen this issue if you have another idea.

**Comment by kikonen** [comment]
Fix:
https://askubuntu.com/questions/662222/why-bracketed-paste-mode-is-enabled-sporadically-in-my-terminal-screen
