### ISSUE TITLE
doesn't support some terminal control chars (eg ^u = kill)

### ISSUE THREAD

**Issue by zenspider** [ruby/debug#650]
Mac OS terminal

* `ruby -v`: ruby 3.1.2p20
* `rdbg -v`: rdbg 1.5.0

**Describe the bug**

I noticed that `^k` and `^y` work (kill-line and yank) as expected, but was surprised that ^u (unix-line-discard) does not.

**To Reproduce**

1. enter debugger
2. type anything
3. control-u

**Expected behavior**

Everything to the left of the cursor should be cleared back to the prompt

**Comment by ko1** [comment]
debug.gem uses Reline which is used by irb for console.
irb doesn't show this issue?

**Comment by zenspider** [comment]
Definitely shows up in IRB as well. I haven't been using it of late because I find the popups very distracting and haven't dug in to figure out if you can turn it off.

Want me to refile over there?

**Comment by st0012** [comment]
@zenspider Regarding the `reline` popup, we're already pushing [the first PR](https://github.com/ruby/reline/pull/413) to address it, which I expect to be merged soon. But we'll still need to make a few other changes to resolve it.

At the mean time, you can disable it by putting `IRB.conf[:USE_AUTOCOMPLETE] = false` in your `PROJECT/.irbrc` or `~/.irbrc`.

**Comment by zenspider** [comment]
Thank you. I just found that and am now tweaking out some other config (I've been dragging my own history truncator along for 15+ years)

**Comment by zenspider** [comment]
ACTUALLY... now that I'm poking around in IRB, this appears fixed. Looking at debug it appears fine too... So I think this was fixed in the latest reline bump:

```
9997 % ruby -v ; rdbg -v; gem list reline 
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
rdbg 1.5.0

*** LOCAL GEMS ***

reline (0.3.1, default: 0.3.0)
```

Can we get @hsbt to tag reline 0.3.1 whenever that was cut?

**Comment by st0012** [comment]
There’s also an issue for the tag: https://github.com/ruby/reline/issues/436

**Comment by st0012** [comment]
@zenspider FYI the tag has been pushed.
