### ISSUE TITLE
Stepping into a specific call on a line

### ISSUE THREAD

**Issue by nilbus** [ruby/debug#655]
**Problem Description**
It can be extremely tedious (and even hard to know how) to step into the intended method call on a line that has many method calls. Consider this sample code with 9 method/variable references:
```ruby
writer.hset(meta_key(user), uuids_key, meta_uuids.excluding(uuid).join(","))
```
If my goal is to step into the `hset` call, I must first `step` into, `finish`, and `step`/`next` into the next call for up to 8 other method calls before I can step into `hset`. It's extremely easy to get lost during this process, especially in unfamiliar code and when it's unclear which references are to methods and which are to local variables.

**Ideas**
I'm interested in your feedback about what would be feasible. Here are some ideas:

1. The [pry-moves][] debugger supports `step <method_name>`: step into method `method_name`, with partial name match supported. ([implementation][]) If given a numeric argument, `step` would continue to step n times. If given a string argument, it would attempt to match step into the method where `__callee__` matches the given pattern.
2. The RubyMine editor provides a [Smart step into][] feature that provides a solution that requires a cursor. Lacking the environment with the cursor, perhaps debug can provide a similar choice via a menu/list of calls on the current line that the user can select from to step into, maybe when the argument is `?`, i.e. `step ?`.

[pry-moves]: https://github.com/garmoshka-mo/pry-moves
[implementation]: https://github.com/garmoshka-mo/pry-moves/blob/master/lib/commands/step.rb
[Smart step into]: https://www.jetbrains.com/help/ruby/stepping-through-the-program.html#smart-step-into

Are any of these feasible? What are your thoughts? Thanks for considering!

**Comment by st0012** [comment]
Debugger supports breaking at an object's method call with the `b[reak]` command. So I think you can do `b writer.hset` and then `c` in this case.

**Comment by nilbus** [comment]
@st0012 that's a really good workaround that I hadn't considered. Thank you!

The first scenario I ran into where I could use it was this, where I wanted to step into `import`:

```ruby
result = described_class.new(operations).import
```

In this case, I couldn't `break described_class.new(operations).import`, because I'd be breaking on a _new_ instance, different than the one that would be hit after `continue`. Instead, I looked up what `described_class` referred to and did `break ThatReferencedClassName#import`, which worked.

While this works (and in the common case without having to do ☝️), the biggest issue I see is that it leaves lingering breakpoints that can be hit later for what was intended to be a transient `step` operation. These need to be manually deleted to keep the program from stopping there as it continues. I think the community would appreciate having this built in.

Regardless, thank you—this is useful in the meantime!

**Comment by nilbus** [comment]
Alternatively, if we could create one-time breakpoints, this might be less effort to implement and still eliminate the biggest drawback to this workaround.

**Comment by ko1** [comment]
I think one-time breakpoint doesn't solve this issue because if the breakpoint is not reached (because of exception and so on) it will be remained.

Extending `step` command is considerable.

```ruby
# c.rb
class C
  def foo
  end
end
```

I think pattern should be
* method name (`step foo` / `step #foo`)
* class/module name the method defined (`step C`)
* path (`step a.rb`)

and combination? `step C#foo`

or only method name?

Note that regexp pattern should be use `/` like `/foo/` on command.
... but I understand typing two `/` is inconvenient on this case.

**Comment by st0012** [comment]
I like the idea of extending `step` command 👍 
Regarding the method signature, I think it should accept what `break` takes:

- `step C#foo`
- `step C.foo`
- `step c.foo`

That'll give users enough options to navigate complicated method calls like

```rb
# step Template#format
# step Diestor.diest
# step template.virtual_path
digest = Digestor.digest(name: template.virtual_path, format: template.format, finder: lookup_context, dependencies: view_cache_dependencies)
```

[source](https://github.com/rails/rails/blob/30363d0b1da86772392ab315ba0afdc65f302817/actionview/lib/action_view/helpers/cache_helper.rb#L249)

**Comment by ko1** [comment]
maybe this feature is breakdown the following features

* introduce "temporary" breakpoint which will be removed just after stopping by any reasons. I'm not sure `break` command can make it (maybe it is not needed. At least there is request).
* make `step XXX` as a shortcut of the following two commands:
  * `break XXX as temporary breakpoint`
  * `continue`

**Comment by nilbus** [comment]
Step XXX maxes sense. “Into” can be implied.

**Comment by ko1** [comment]
I choose `step into <name>` because there are already `step back` and `step reset` commands.
