### ISSUE TITLE
How Might I Access Convenience Methods in ~/.rdbgrc?

### ISSUE THREAD

**Issue by mzagaja** [ruby/debug#657]
Based on some advice on StackOverflow I have added a convenience method to my `~/.irbrc` as follows:

```ruby
def pbcopy(arg)
  out = arg.is_a?(String) ? arg : arg.inspect
  IO.popen('pbcopy', 'w') { |io| io.puts out }
  puts out
  true
end
```

I would also like to be able to use this convenience method for sending text to the MacOS clipboard in debug. I tried adding this to `~/.rdbgrc` in the same manner, but trying to execute `pbcopy response.body` in a session started with `rdbg -c -- bundle exec rspec spec/requests/v2_account_spec.rb` fails. Is there a different way I should access this from the console? I am currently just invoking irb from the debugger to do this, but would be nice to save a step.

**Comment by st0012** [comment]
`.rdbgrc` expects debugger commands. And for Ruby code, the file name needs to be `~/.rdbgrc.rb`.

**Comment by mzagaja** [comment]
Renaming from `~/.rdbgrc` to `~/.rdbgrc.rb` worked. Thank you! 🎉
