### ISSUE TITLE
Unexpected child debugging session when starting remote debuggee with `RUBYOPT=-rdebug/*`

### ISSUE THREAD

**Issue by st0012** [ruby/debug#663]
**Describe the bug**

Some criteria for this issue:

1. Use `RUBYOPT=-rdebug/open` to load the debugger in remote mode.
2. The program runs another Ruby process like `system("bundle exec rake")`

When the above happens at the same time, it'll trigger double debugging sessions. I recorded a video to demo this:

https://user-images.githubusercontent.com/5079556/175811942-bd585b50-edc0-45a8-9bc6-b666d1e359bf.mov

This is annoying because the second session starts independently and hangs the program, until we connect to and disable it.

And this can [happens to Rails apps](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/migration.rb#L652).

I'm not sure it's at fault of the debugger as that's how ENV vars are passed to child processes. But perhaps we can do something from the debugger to prevent it?

**To Reproduce**

**bar.rb**

```rb
puts "bar"
```

**target.rb**

```rb
result = `ruby bar.rb`

puts(result)
```

**terminal1**

```shell
RUBYOPT=-rdebug/open ruby -Ilib target.rb
```
**terminal2**

```shell
rdbg -A
```

**Expected behavior**

The second process shouldn't start a debugging session.

**Comment by ko1** [comment]
Okay. Restore RUBYOPT while requiring `session.rb`.

**Comment by st0012** [comment]
@ko1 Thanks for the fix. But I just tested the PR but it doesn't solve the example I mentioned here, as it's not passed by the `rdbg` binary. Do you think there's a way to solve that case too?

**Comment by ko1** [comment]
Ah, I see. On this case, we can't recognize it should be kept or not.

Another idea is set `RUBY_DEBUG_ENABLE=0` at session.rb and child processes can not load debug.rb, but it also prohibits invoking debugger if it is needed.

Another idea is removing `-r debug/...` but I'm afraid it can be done correctly.

**Comment by st0012** [comment]
@ko1 I see, thank you.
