### ISSUE TITLE
Slow local variables load in VSCode due to inspect of large variables

### ISSUE THREAD

**Issue by rockorequin** [ruby/debug#674]
**Your environment**

* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
* rdbg commit b8f799f212348da3da0712f188c5dae6d33d38b3 from master

**Describe the bug**
VSCode is very slow to load the local variables window in my app when it stops at a breakpoint where the self object has an instance variable of type RubyXL::Worksheet (with images in it) as well as an instance variable for the parent workbook in the self because the obj.inspect in rdbg's safe_inspect is returning a very large string. See also https://github.com/ruby/debug/issues/635#issuecomment-1138477194 where the obj.inspect for a worksheet in the backtrace was taking nine or ten minutes to return a 16 MB string, and the comments at https://github.com/ruby/debug/issues/635#issuecomment-1171986439 and after.

I am running the debugger in a WSL instance, so this might be slowing things down more than running it natively.

**Expected behavior**
VSCode should be able to load the local variables window in a reasonable time (preferably micro or milliseconds) rather than freezing.

**Additional context**
One solution is to use the same fix as for https://github.com/ruby/debug/issues/635 by using the LimitedPP.pp call instead of obj.inspect in safe_inspect, eg:

```
 def self.safe_inspect obj, max_length: SHORT_INSPECT_LENGTH, short: false
    if short
      LimitedPP.pp(obj, max_length)
    else
      #obj.inspect
      LimitedPP.pp(obj, 32768)
    end

```

With this change, the local variables window loads in VSCode in a reasonable time.

I tried using a limit of up to 128 kB and the local variables window is noticeably slow to load but still of the order of a second.

**Comment by ko1** [comment]
Thank you the report. I try to limit in 4KB. Is it enough?

**Comment by rockorequin** [comment]
Thanks, I'm sure 4KB is plenty.
