### ISSUE TITLE
why my debugger always hang?

### ISSUE THREAD

**Issue by laptopmutia** [ruby/debug#735]
Ruby 3.1.2

rails (7.0.3.1)
debug (1.6.1)
  irb (>= 1.3.6)
  reline (>= 0.3.1)

When I use debugger then write some code
like this
```
(ruby) request.env["omniauth.auth"]
```

it hang and never do anything not even throwing error
but sometimes it returning syntax error

until I manually kill the process

**Comment by st0012** [comment]
It may be caused by https://github.com/ruby/debug/issues/725, which has been fixed in `1.6.2`. Can you upgrade and try again?

**Comment by slayer** [comment]
Same issue with `1.6.2` - simple method call hangs for ~1 minute

**Comment by prostko** [comment]
+1. Hanging and crashing happens more than it doesn't.

**Comment by st0012** [comment]
Can you provide a demo app that reproduces the crashing?

**Comment by laptopmutia** [comment]
for me 1.6.2 fixed my problem

**Comment by ko1** [comment]
can we close this issue?

**Comment by laptopmutia** [comment]
yea

**Comment by prostko** [comment]
@ko1 I'm still experiencing this issue pretty frequently. I'm happy to open a separate issue when I get some time and add a complete demo app and steps to reproduce. 

Thanks for your work on this 👍

**Comment by ko1** [comment]
@prostko Thank you and sorry bothering you.

**Comment by laptopmutia** [comment]
this issues seems back again, I'm wondering even though I have use 1.6.2

**Comment by onesneakymofo** [comment]
Macbook Air M2 here chiming in - version 1.7.1.

I am getting 

```
"No live threads left. Deadlock?\n5 threads, 5 sleeps current...
```
when using `binding.break`

**Comment by drewlustro** [comment]
Also seeing this. M1 Max, version 1.8.0

Seeing same as @onesneakymofo
