### ISSUE TITLE
Feature request: Make `fs_map` work with UnixDomainServer

### ISSUE THREAD

**Issue by jvilk-stripe** [ruby/debug#741]
**Your proposal**
Make `fs_map` work with `UnixDomainServer`. Right now, the code disables this feature for `UnixDomainServer`:

https://github.com/ruby/debug/blob/master/lib/debug/server_dap.rb#L131

**Additional context**

Stripe runs `ruby` on a remote server and VS Code on a laptop. We proxy the unix domain socket from server to laptop, and need to use the fs map feature to translate file paths.

**Comment by ko1** [comment]
Maybe #745 fixes it.
