### ISSUE TITLE
Feature request: respect `skip_path` when returning backtraces

### ISSUE THREAD

**Issue by marianosimone** [ruby/debug#748]
**Your proposal**
The documentation for `skip_path` says:

> Skip showing/entering frames for given paths

However, it only works for entering frames while doing step-by-step debugging and displaying the backtrace through `backtrace` (as implemented [here](https://github.com/ruby/debug/blob/2cb44483c681f6806bf6843a8f996d3a10d0e42c/lib/debug/thread_client.rb#L665)). However, it does not work when requesting the stacktrace through DAP [here](https://github.com/ruby/debug/blob/2cb44483c681f6806bf6843a8f996d3a10d0e42c/lib/debug/server_dap.rb#L699-L732).

**Comment by ko1** [comment]
#749 fixed it? Please reopen if I misunderstood.
