### ISSUE TITLE
`next` stops in the wrong place when blocks are called

### ISSUE THREAD

**Issue by marianosimone** [ruby/debug#763]
**Your environment**

* `ruby -v`:  2.7.2p137
* `rdbg -v`: 1.6.2

**To Reproduce**
For a simple case:
1. Create a file like:
```ruby
def with_block
    yield
end
   
with_block do
    1
end
puts("`next` should stop here")
```
2. Add a breakpoint in line 5
3. Try to move to `next`
4. See the debugger stop at line 6 (and then 7, and 3)

For more complex cases:
1. Create a file like:
```ruby
class Bar
  define_method("dynamic") do
    true
  end

  def regular; false; end
end

def foo(a, b, c); end

bar = Bar.new
foo(
  bar.regular,
  bar.dynamic, # `next` stops here
  bar.regular
)
puts("`next` should stop here")
```
2. Add a breakpoint in line 12 (where the call to `foo` is)
6. Try to move to `next`
7. See the debugger stop at line 14

**Expected behavior**
The debugger should stop at line 8 in the simple example, and 17 in the complex one

**Additional context**
I included non-dynamically-defined methods, to show that `next` only behaves incorrectly for the dynamically-defined ones (as it doesn't stop at line 13 nor 15)

**Comment by marianosimone** [comment]
Here's a protocol test that should pass when the issue is fixed:

```ruby
# frozen_string_literal: true

require_relative '../support/protocol_test_case'

module DEBUGGER__
  class NextDynamicMethodTest < ProtocolTestCase
    PROGRAM = <<~RUBY
       1| class Bar
       2|   define_method("dynamic") do
       3|     "dynamic"
       4|   end
       5|   
       6|   def regular
       7|     "regular"
       8|   end
       9| end
      10|   
      11| def foo(a, b, c); end
      12|   
      13| bar = Bar.new
      14| foo(
      15|   bar.regular,
      16|   bar.dynamic,
      17|   bar.regular
      18| )
      19| bar
    RUBY

    def test_next_goes_to_the_next_statement
      run_protocol_scenario PROGRAM do
        req_next
        assert_line_num 2

        assert_locals_result(
          [
            { name: "%self", value: "Bar", type: "Class" },
          ]
        )
        req_next
        assert_line_num 6

        assert_locals_result(
          [
            { name: "%self", value: "Bar", type: "Class" },
          ]
        )
        req_next
        assert_line_num 11

        assert_locals_result(
          [
            { name: "%self", value: "main", type: "Object" },
            { name: "bar", value: "nil", type: "NilClass" }
          ]
        )
        req_next
        assert_line_num 13

        assert_locals_result(
          [
            { name: "%self", value: "main", type: "Object" },
            { name: "bar", value: "nil", type: "NilClass" }
          ]
        )

        req_next
        assert_line_num 14

        assert_locals_result(
          [
            { name: "%self", value: "main", type: "Object" },
            { name: "bar", value: /#<Bar/, type: "Bar" }
          ]
        )

        req_next
        assert_line_num 19

        assert_locals_result(
          [
            { name: "%self", value: "main", type: "Object" },
            { name: "bar", value: /#<Bar/, type: "Bar" }
          ]
        )
        req_terminate_debuggee
      end
    end
  end
end
```ruby

**Comment by marianosimone** [comment]
cc @WillHalto. Just a heads up that https://github.com/ruby/debug/pull/743 doesn't seem to make this worse, but given that you are already there and have some context, you might find it interesting.

**Comment by st0012** [comment]
A small tip: you can write the reproduction steps down like:

```rb
debugger(do: "b 6 ;; c ;; n ;; n ;; n")

def with_block
    yield
end

with_block do
    1
end

puts("`next` should stop here")
```

In this case, we only need to run

```shell
$ rdbg -n target.rb
```

And the reproduction steps can be executed automatically.

If you don't want to modify the script directly, you can achieve it with `rdbg -e` too:

```rb
def with_block
    yield
end

with_block do
    1
end

puts("`next` should stop here")
```

```shell
$ rdbg -e "b 5 ;; c ;; n ;; n ;; n" target.rb
```

**Comment by st0012** [comment]
For the complicated example, I think it's caused by a bug in older Ruby versions.

**Example**

```rb
TracePoint.new(:b_return, :return) do |tp|
  puts [tp.event, caller_locations(1, 1).first].to_s
end.enable

class Bar
  define_method("dynamic") do
    true
  end # line 8
end

Bar.new.dynamic # line 11
```

If you execute this script with Ruby < 3.1, you'll get

```
❯ ruby test.rb
[:b_return, "test.rb:8:in `block in <class:Bar>'"]
[:return, "test.rb:11:in `<main>'"]
```

And you can see that `b_return` and `return` events' line numbers don't match. Ideally, they should both be `8`.

However, if you run it with Ruby 3.1, they do match

```
❯ ruby test.rb
[:b_return, "test.rb:8:in `block in <class:Bar>'"]
[:return, "test.rb:8:in `block in <class:Bar>'"]
```

So I think it's more like a bug in Ruby, but we may workaround it in `debug`.

**Comment by ko1** [comment]
It solved on Ruby 3.1.0 and later.
I agree it is an issue, but not so big problem I think so I left it.
Please reopen it if it is so important issue.

**Comment by marianosimone** [comment]
I don't know what your policy is in supporting Ruby < 3.1.0... but, as it is, with this issue and https://github.com/ruby/debug/issues/760, the debugger has a really poor experience.

Given that we still have 6 months until the end of life of Ruby 2.6 (and no date for 2.7), I'd argue for at least keeping this open, and try to fix it.

**Comment by st0012** [comment]
Last time I tested, the simple case's issue also happened with `Ruby 3.1+` so it needs more investigation.

```rb
def with_block
    yield
end
   
with_block do
    1
end
puts("`next` should stop here")
```

So based on that I think we should keep this issue opened until we're clear on both cases' causes.

**Comment by marianosimone** [comment]
It's also worth mentioning that, for anyone using [Sorbet](https://sorbet.org), trying to step with `next` always requires two steps. This is because Sorbet signatures are essentially wrapping methods in a block. Take the following example:

```
sig {returns(T::Boolean)}
def does_it_work?
  false
end

value = does_it_work?
puts("Does it work? #{value}")
``` 

Trying to step over 6 requires two `next`

**Comment by ko1** [comment]
I think additional `next` is not big problem but you think it is a big problem?

**Comment by marianosimone** [comment]
There are actually 2 problems (as identified by @st0012 above):

1. Extra steps when a block is involved (as in Sorbet). This might not seem like much, but if you are debugging a codebase where everything has a signature, it's essentially 2 nexts *for each line* you want to step over
2. `next` going to the wrong place

They are definitely a very bad experience when debugging anything but a trivial codebase

**Comment by ko1** [comment]
I understand the issue.

```ruby
def iter
  yield
end # (iter/end)

iter do
  1
end # (*) Now stopping here

puts("`next` should stop here") # (putline)
```

* For a person who think the block is function, the `next` line of `(*)` should be `(iter/end)`. They have interest how `iter` is implemented.
* For a person who think the block is a loop (or code block) of caller context (top on this case), the `next` line should be `(putline)`. They don't have interest how `iter` is implemented.

Options:

1. `next` should ignore the `iter` internal and jump to `(putline)` (maybe the author of this issue wants)
2. `next` should not ignore `iter` internal and jump to `(iter/end)` (current behavior)

Now, `next` command consider the block is literally `next`, so option 1 seems preferable.

**Comment by marianosimone** [comment]
In the case above, 2 (at the line with `end`) is never what I'd expect to happen.

What I would expect is 1 (thus this ticket), but I'd be OK (as in: "I don't like this much, but at least doesn't surprise me") with either stopping inside the `iter` function (the line with `yield`) or inside the block (the line with `1`).

**Comment by ko1** [comment]
> with either stopping inside the iter function (the line with yield) or inside the block (the line with 1).

When stopping at line `(*)`, it never stop at `yield` or `1` because they are passed lines.

**Comment by ko1** [comment]
v1.7.0 may fix this issue.

**Comment by marianosimone** [comment]
I can confirm that, at least in ruby 2.7, this is still not fixed. I've simplified the test enough to this:

```ruby
class NextDynamicMethodTest < ProtocolTestCase
    PROGRAM = <<~RUBY
       1| class Bar
       2|   define_method("dynamic") do
       3|     "dynamic"
       4|   end
       5|
       6|   def regular
       7|     "regular"
       8|   end
       9| end
      10|
      11| def foo(a, b, c); end
      12|
      13| bar = Bar.new
      14| foo(
      15|   bar.regular,
      16|   bar.dynamic,
      17|   bar.regular
      18| )
      19| bar
    RUBY

    def test_next_goes_to_the_next_statement
      run_protocol_scenario PROGRAM do
        req_add_breakpoint 14
        req_continue
        assert_line_num 14
        req_next
        assert_line_num 19 # When `TracePoint` returns the wrong number for :return after :b_return, this is 16

        req_terminate_debuggee
      end
    end
end
```

**Comment by ko1** [comment]
Thank you I verified

* 3.0 -> failed
* 3.1, 3.2 (released soon) -> success

**Comment by marianosimone** [comment]
> Thank you I verified
> 
> * 3.0 -> failed
> * 3.1, 3.2 (released soon) -> success

Coming back to this after I'm using Ruby 3.1, and I can verify that the issue is solved
