### ISSUE TITLE
What about adding an option to disable command repeat (on Enter key)?

### ISSUE THREAD

**Issue by blocknotes** [ruby/debug#764]
**Your proposal**
It's a minor thing but it would be nice to have an option to disable command repeat when the Enter key is pressed in debug console.

**Additional context**
For users coming from `pry` it could be confusing to have the repeat feature on Enter.
Also, IMO, it's not comfortable repeating some commands that have side-effects. Ex. `SomeModel.create! name: 'A test'`

**Comment by blocknotes** [comment]
I could try a PR if you like.

Perhaps it could be something like updating this point:
https://github.com/ruby/debug/blob/master/lib/debug/session.rb#L407

to:

```rb
@repl_prev_line = line unless ENV['RUBY_DEBUG_NO_REPEAT_ON_ENTER']
```

**Comment by ko1** [comment]
* It is useful for `step`/`next`/... and so on
* I also understand the Ruby script like `SomeModel.create! name: 'A test'` is not confortable.

Your request is adding new option to stop the repeating the command, but another option is don't repeat Ruby script.
I'm okay for that.

**Comment by ko1** [comment]
#793 limited the repeatable commands, like `step`, `next`, ... and Ruby expression is no longer repeated with empty line.
If you feel inconvenience with it, please reopen or renew an issue.
