### ISSUE TITLE
`rdbg -c -- <cmd>` fails if cmd starts with environment variables

### ISSUE THREAD

**Issue by st0012** [ruby/debug#795]
**Your environment**

* `ruby -v`: `3.1.2`
* `rdbg -v`: `1.6.3`

**Describe the bug**

(I'm not sure if it's a bug, but I'd like to confirm if this is intentional)

I'm trying to conditionally append `rdbg -c --` before user's commands defined in `Procfile`, so users don't need to manually append them when they want to debug. (e.g. users can type `debug <service>` and then the command will be run with debugger activated)
This works with commands like `bundle exec sidekiq` or `bin/rails s`. But it causes error when user appends environment variables to the command like `ENV=VAL bundle exec sidekiq`.

```
/home/spin/.bundle/code-db/gems/debug-1.6.3/exe/rdbg:36:in `exec': No such file or directory - ENV=VAL (Errno::ENOENT)
```

This is because `ruby/debug` uses `ARGV.shift` to get the [debuggee command](https://github.com/ruby/debug/blob/e7c37486ff9579251e5d25645b8d38ec96708f12/exe/rdbg#L14).

Currently we're trying to workaround this by quoting user's commands, so it'll be `rdbg -c -- 'ENV=VAL bundle exec sidekiq'`. But this won't work if the user also quotes something in the command.

**To Reproduce**

```
$ rdbg -c -- ENV=VAL bundle exec ruby -e "puts '123'"
```

**Expected behavior**

I expect appending environment variables to work too.

**Comment by ko1** [comment]
I think the current behavior is not a bug. For example,

```shell
$ bundle exec -- E=1 ruby -e 'p ENV["E"]'
bundler: command not found: E=1

$ bundle exec -- 'E=1 ruby -e "p ENV[?E]"'
"1"
```

I didn't know the background of this behavior so it needs some survey.

**Comment by st0012** [comment]
Thanks for the example. Now I think the error is also not about `ARGV.shift`. It's because that `Kernel.exec` always treat the first argument as the command:

```rb
args = ARGV

puts "args: #{args}"

Kernel.exec(*args)
```

```
$ ruby test.rb ENV=VAL ruby -e "puts ENV['ENV']"
args: ["ENV=VAL", "ruby", "-e", "puts ENV['ENV']"]
test.rb:5:in `exec': No such file or directory - ENV=VAL (Errno::ENOENT)
        from test.rb:5:in `<main>'
```

I agree that this is not a bug, nor something should be taken care of by the debugger.

**Comment by ko1** [comment]
Technically maybe it is feasible and in some cases it seems convenient.
I want to know the disadvantages if there are (and why other tools doesn't support it).

**Comment by st0012** [comment]
Yes it'd be very convenient if `rdbg` can do something like extracting env vars before passing the input to `ARGV`. But I'm not sure if that's the only case that needs special support and/or it'd cause new problems.
At least now users can find this issue and understand it's not a bug and know a possible way to workaround it.
