### ISSUE TITLE
`step into XXX` to `until XXX`

### ISSUE THREAD

**Issue by ko1** [ruby/debug#796]
We introduced `step into XXX` for #655 but I realized that `step into` is a bit strange for me because `step` command should stop at the next operation (line, call, ...) immediately.

Also `into XXX` does not make sense if the `XXX` is called after returning from the current frame.

```ruby
def foo
  # break here
end

foo
bar
```

If we stop at the line 2 (`break here` line) and dispatch `step into bar`, then

* return from `foo`
* call `bar`
* break at the first line of `bar`

I think `continue until XXX`, `continue to XXX` or just `continue XXX` is another alternative but not sure it makes sense a lot.
Maybe `break YYY` does not make sense too.

`step until XXX` is another candidate. It is similar to `step 10` (repeat step 10 times).

Not concluded but I want to fix current name.

**Comment by ko1** [comment]
`until` command on gdb is similar https://sourceware.org/gdb/download/onlinedocs/gdb/Continuing-and-Stepping.html so we should implement `until` command.

So `step into XXX` should be `until XXX` or `u XXX`.

**Comment by ko1** [comment]
* `until`: Continue the program until it reaches to the next line even if at the end of loop. `next` command stops the program at the beginning of the loop, but `until` command stops just after loop.
* `until <loc>`: Continue the program until it reaches to the `<loc>` *or* it returns from the current frame (~= `finish`).

**Comment by ko1** [comment]
gdb skips the recursive function calls but I think it is okay to respect the any recursive call (and `advance` command is too much).

**Comment by ko1** [comment]
gdb's `until` doesn't make pending temporary breakpoint for the unknown location (`break` makes pending breakpoints).
we can skip unknown location. But not clear that *unknown* method. maybe we can show error if the symbol in `Symbal.all_symbols` doesn't include the given location.

**Comment by ko1** [comment]
https://sourceware.org/gdb/current/onlinedocs/gdb/Jumping.html
Known `jump` command doesn't do the proposed behavior.

**Comment by bquorning** [comment]
> I think `continue until XXX`, `continue to XXX` or just `continue XXX` is another alternative but not sure it makes sense a lot.

Byebug actually uses the `continue XXX` syntax, and when using the debug gem I always hit `c 42` instead of `u 42` because of muscle memory.
