### ISSUE TITLE
Weird stepping behaviour when used with `puma 6.0`

### ISSUE THREAD

**Issue by st0012** [ruby/debug#799]
**Your environment**

* `ruby -v`: `3.1.2`
* `rdbg -v`:  [Current master: a402e73](https://github.com/ruby/debug/commit/a402e7304db8b78e8b7ee1e2142e47214b99cc72) (but the issue can be reproduced with commits as early as https://github.com/ruby/debug/commit/c3d92574d82ede7dab4bcf2dbe8203c5a0b1fbcb)

**Describe the bug**

When using the latest `ruby/debug` with `Puma 6.0+`, stepping over (or `next` command) could enter weird places (e.g. `zeitwerk`'s internal). For example:

```
[2, 11] in ~/projects/debug-issue/app/controllers/posts_controller.rb
     2|   before_action :set_post, only: %i[ show edit update destroy ]
     3|
     4|   # GET /posts or /posts.json
     5|   def index
     6|     binding.b
=>   7|     @posts = Post.all
     8|     a = 1
     9|     b = 2
    10|   end
    11|
=>#0    PostsController#index at ~/projects/debug-issue/app/controllers/posts_controller.rb:7
  #1    ActionController::BasicImplicitRender#send_action(method="index", args=[]) at ~/.gem/ruby/3.1.2/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6
  # and 76 frames (use `bt' command for all frames)
(rdbg) n    # next command
[23, 32] in ~/.gem/ruby/3.1.2/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb
    23|     alias_method :zeitwerk_original_require, :require
    24|   end
    25|
    26|   # @sig (String) -> true | false
    27|   def require(path)
=>  28|     if loader = Zeitwerk::Registry.loader_for(path)
    29|       if path.end_with?(".rb")
    30|         required = zeitwerk_original_require(path)
    31|         loader.on_file_autoloaded(path) if required
    32|         required
=>#0    Kernel#require(path="/Users/hung-wulo/projects/debug-issue/ap...) at ~/.gem/ruby/3.1.2/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:28
  #1    PostsController#index at ~/projects/debug-issue/app/controllers/posts_controller.rb:7
  # and 77 frames (use `bt' command for all frames)
```

**To Reproduce**

Please clone this [vanilla Rails app](https://github.com/st0012/debug-issue) and follow the instructions in the readme.

**Expected behavior**

Typing `n` should go to line 8 instead of entering `zeitwerk`'s internal.

**Additional context**

- It's highly related to https://github.com/ruby/debug/pull/746. cc @WillHalto
- It works fine with `puma 5.0`

**Comment by ko1** [comment]
Thank you, so I'll revert #746, unfortunately.

I'll introduce another technique for Ruby 3.2, but 3.1 or before has performance issue.

**Comment by st0012** [comment]
@ko1 That sounds good, thank you 🙏

**Comment by ko1** [comment]
I confirmed that without #746 it stops at next line.

**Comment by st0012** [comment]
I can confirm that it now works as expected. Thanks for the fix 👍
