### ISSUE TITLE
Escape character for Ruby REPL

### ISSUE THREAD

**Issue by ko1** [ruby/debug#801]
VSCode Debug Console supports Ruby REPL and it doesn't accept debug commands.
I want to introduce an escape character to pass debug commands on that REPL.
For example, make `#` as an escape character and `#info c /foo/` is recognized as `info c /foo/` debug command.

Possible character ideas:

* Invalid Ruby syntax
  * `.` (SQLite3, pry's shell escape)
  * `,` (Gauche)
  * `]` (Julia)
  * `)`
  * `>`
* Valid Ruby syntax but maybe not used on Ruby REPL
  * `#` (Ocaml)
  * `:` (Haskell)
  * `%` (Jupyter)
  * `\` (PostgreSQL)

`()` is users of the escape character. It seems no *common* escape character.
Now I'm positive to use `#` because we repeat to write `#foo` for comments.

**Comment by ko1** [comment]
Another idea is using `debugger` method like `debugger do: 'info c /foo'`.

**Comment by wenderjean** [comment]
Even though the use of `#` sounds very natural to me as a Ruby developer, I'm not sure whether `Debug Console` would interpret it like a simple comment directly or if it would send it to the `process_command` method and we can interpret it.

Another option that sounds very natural is the Haskell version like `:info c /test/`

The `debugger do: 'info c /foo'` is also a good option even though I believe using a character would cause less friction.

**Comment by ko1** [comment]
* One-push key
  * `. , ] \`
* WIth-Shift
  * `) > # : %`
* QWERTY
  * Right:  `. , ] ) > : \`
  * Left: `# %`

**Comment by ko1** [comment]
> Even though the use of # sounds very natural to me as a Ruby developer, I'm not sure whether Debug Console would interpret it like a simple comment directly or if it would send it to the process_command method and we can interpret it.

Do you write comments on Ruby REPL (irb forexample)?

**Comment by ko1** [comment]
Ah I forget that so I should not use `.` to avoid conflict.

**Comment by ko1** [comment]
I realized that `#` can be used for copy&paste the code block to the REPL input.

**Comment by wenderjean** [comment]
> Do you write comments on Ruby REPL (irb forexample)?

I don't write them, I just noticed that `irb` does not raise a SyntaxError when I try to use `#` on it, what suggested to me that the REPL might interpret it like a simple comment and we would never reach `process_command` at all. :)

**Comment by ko1** [comment]
Samples:

![image](https://user-images.githubusercontent.com/9558/201846671-b306770d-eb10-4e5d-a610-b8f9daae0935.png)
![image](https://user-images.githubusercontent.com/9558/201846801-b76dfbf9-f43e-40d0-98ee-071cfb478121.png)
![image](https://user-images.githubusercontent.com/9558/201846881-6522d1b8-a66f-4eca-8949-9b55f74cd40a.png)
![image](https://user-images.githubusercontent.com/9558/201846927-791bfe87-b347-4ccb-8510-897481a8cd08.png)
![image](https://user-images.githubusercontent.com/9558/201847046-71ab2ab1-cf6d-4ff1-b926-59bf77d3caad.png)

**Comment by ko1** [comment]
Comments from other ruby committers:

* `:` is used for example `::Object` or `:foo.succ`
* `%` is also used (`%X...X`)
* `,` is ugly
* `>` is consistent with VSCode command pallete (+1)
* Duplicated `>` (DEBUG console `>` and escape `>`) is ugly too
  * `)`, `]` are also bit ugly.
* `#foo` seems meta command maybe because of C's pragma (`#include` and so on) (+1)
* If we extend the meta-key to irb, copy&paste code block with `#` comment line will conflict with it (I wrote it is issue on VSCode https://github.com/ruby/debug/issues/801#issuecomment-1314325358 but I find that VSCode debug console extend the text input on copy&paste so maybe no problem)
* but it can be problem if we want to mix the Ruby code and debug commands in multiple lines
  * ```
    foo
    # debug command 1
    bar
    # debug command 2
    # debug command 3
    baz
    ```

No conclusion yet.

**Comment by wenderjean** [comment]
I don't think `,` that ugly and it is not that far from what pry does with `.` :)

**Comment by ko1** [comment]
> Update: I spent some time getting familiar with dap tests and it seems \ is escaped before reaching the server, I'd need a bit more time to investigate but in that case, it seems we end up with , 🤔

Great information!

**Comment by ko1** [comment]
Try with `,`.
