### ISSUE TITLE
output is garbled on Emacs shell

### ISSUE THREAD

**Issue by freesteph** [ruby/debug#878]
**Your environment**

* `ruby -v`: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
* `rdbg -v`: rdbg 1.7.1

**Describe the bug**
The input into the `debug` prompt is repeated back to the tty and confuses the output. Very similar to https://github.com/ruby/debug/issues/603.

```ruby
require 'debug'

def func(x)
  debugger

  x + 2
end

func(3)
```

Trying to run `x.inspect`:

```
19:39 ~/build/freesteph/sandbox/ruby-debug-output-emacs £  bundle exec ruby main.rb
[1, 9] in main.rb
     1| require 'debug'
     2| 
     3| def func(x)
=>   4|   debugger
     5| 
     6|   x + 2
     7| end
     8| 
     9| func(3)
=>#0	Object#func(x=3) at main.rb:4
  #1	<main> at main.rb:9
(rdbg) x.inspect
(rdbg) x(ruby) x.(ruby) x.i(ruby) x.in(ruby) x.ins(ruby) x.insp(ruby) x.inspe(ruby) x.inspec(ruby) x.inspect"3"
(rdbg) 
```
**To Reproduce**
Use a dumb terminal and try and use debug.

**Expected behavior**
The input I type shouldn't be repeated back to me, and then my output wouldn't be garbled.

**Additional context**
I don't think it's necessary `debug` that's responsible for this behaviour but it might be the underlying terminal library that's not honouring the `DUMB` env var that Emacs and others might set to indicate the terminal is... well, dumb. Either way I can't find a solution so parking it here to help out others in the meantime.

**Comment by freesteph** [comment]
sorry just as I posted the issue I tried to run `irb`and it is indeed a problem with `irb` which exhibits the same behaviour without debug. Sorry about the trouble.

**Comment by freesteph** [comment]
For anyone stumbling across this, I've explored two solutions:

- setting `IRB.conf[:PROMPT_MODE] = :INF_RUBY` in a `~/.irbrc` configuration file seems to work when running standalone IRB, but *not* as part of a `debug` session;
- disabling reline with `RUBY_DEBUG_NO_RELINE=true` in your program environment does the trick.

**Comment by kisp** [comment]
> * disabling reline with `RUBY_DEBUG_NO_RELINE=true` in your program environment does the trick.

Thanks for this! It makes it work for me as well. :+1:
