### ISSUE TITLE
Changelog as file

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [ruby/debug#891]
It would be nice to have the Changelog as a file instead of using the description on the Github releases.

* It is easier to search across several versions' changelogs, when in a file.
* It is tracked by git, so the changelog text can also be reviewed, along with the change that causes the line to be added.

**Comment by runephilosof-karnovgroup** [comment]
Also, it is portable: Should you choose to move from Github to another git repository, the changelogs will just be there.

**Comment by ko1** [comment]
The Github support tool is very helpful to write a release note, so now I want to use it.
With it, maybe the VERSION tag can't contain the release note commit.
