### ISSUE TITLE
Console evaluation in Chrome devtools debugging session

### ISSUE THREAD

**Issue by nilbus** [ruby/debug#894]
When debugging via `open chrome`, I can step through code and set breakpoints fine, but when I enter even 1 character into Chrome's console to test evaluating something, the debugger crashes and its attached ruby process with it.

```
 (eval):1:in `block in process_protocol_request': No such file or directory @ rb_sysopen - -b (Errno::ENOENT)
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/server_cdp.rb:759:in `eval'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/server_cdp.rb:759:in `block in process_protocol_request'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/server_cdp.rb:758:in `map'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/server_cdp.rb:758:in `process_protocol_request'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:424:in `wait_command'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:377:in `block in wait_command_loop'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:376:in `loop'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:376:in `wait_command_loop'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:342:in `process_event'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:235:in `session_server_main'
         from /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:197:in `block in activate'
```
The error is raised at https://github.com/ruby/debug/blob/0fcfc28acae33ec1c08068fb7c33703cfa681fa7/lib/debug/server_cdp.rb#L759

I haven't determined yet what `name.to_s` evaluates to.

Are you able to reproduce this? If not, I can attempt to set up an environment in which it's reproducible.

Thanks!

**Comment by nilbus** [comment]
🤔 I found that I'm having this issue in one environment but not another. I'll see whether I can find time to trace down what's wrong in the environment where it's broken.

**Comment by ono-max** [comment]
I think that https://github.com/ruby/debug/pull/893 fixes this issue.

If you have any problem, please reopen or mention me. Thank you.
