### ISSUE TITLE
VS Code: The evaluation result for debug command is not returned when closing VARIABLES view

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#896]
**Your environment**

* `ruby -v`: 
* ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
* `rdbg -v`:
* rdbg 1.7.1

**To Reproduce**
Close VARIABLES View as follows.

![Screen Shot 2023-02-13 at 21 49 25](https://user-images.githubusercontent.com/59436572/218461862-d4dd7523-41a4-4de9-93d8-84a7b83ffcff.png)

Debug the following scripts.

```ruby
a=1 # set breakpoint here.
b=2
c=3
```

Then enter `,n` in the debug console.

**Expected behavior**

It should stop at the second line.

**Additional context**

**Comment by ko1** [comment]
Maybe fixed on 211b319c74dad210646df6180a529942bc37ad4d
