### ISSUE TITLE
memory leak / retention

### ISSUE THREAD

**Issue by nilbus** [ruby/debug#899]
**Your environment**

* `ruby -v`: `ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]`
* `rdbg -v`: `rdbg 1.7.1`

**Describe the bug**
After shipping a Rails app with the debug gem bundled and required via `debug/open_nonstop`, memory usage grew with each request.

![memory usage before and steadily growing after bundling debug](https://user-images.githubusercontent.com/64751/219701633-71cf8e87-d925-4998-bbbf-3626a586e408.png)

**Expected behavior**
Memory is not retained during the request cycle

---

Our goal is to have the Rails process ready for a debugger process to attach in staging environments.

Do you have an idea of what memory might be allocated and retained across requests? Can this be worked around?

**Comment by jaynetics** [comment]
i can confirm this is a problem.

i compared multiple memory dumps over time as described [here](http://stratus3d.com/blog/2020/08/11/effective-debugging-of-memory-leaks-in-ruby/) and found these leaks:

Retained 49881 ARRAY objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/thread_client.rb:111](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/thread_client.rb#L111)
Retained 49867 HASH objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/thread_client.rb:119](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/thread_client.rb#L119)
Retained 49858 OBJECT objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/session.rb:1488](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/session.rb#L1488)
Retained 49853 HASH objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/thread_client.rb:113](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/thread_client.rb#L113)
Retained 49849 DATA objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/session.rb:1488](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/session.rb#L1488)
Retained 49840 HASH objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/thread_client.rb:114](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/thread_client.rb#L114)
Retained 49835 DATA objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/thread_client.rb:112](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/thread_client.rb#L112)
Retained 49809 ARRAY objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/session.rb:1488](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/session.rb#L1488)
Retained 33265 IMEMO objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:45
Retained 33259 ARRAY objects at: /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:223
Retained 33251 ARRAY objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:45
Retained 33241 DATA objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:46
Retained 33231 ARRAY objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:46
Retained 33229 DATA objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/shell.rb:45
Retained 16650 DATA objects at: /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:223
Retained 16641 ARRAY objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/tool.rb:111
Retained 16634 FILE objects at: /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:97
Retained 16633 FILE objects at: /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:93
Retained 16628 OBJECT objects at: /app/vendor/bundle/ruby/3.1.0/gems/mini_magick-4.11.0/lib/mini_magick/tool.rb:91

there is some symmetry of the debug object numbers with the mini_magick + open3 numbers, so maybe there is a memory leak in some gems, such as mini_magick (see also https://github.com/minimagick/minimagick/pull/544) and that leak is greatly exacerbated by the debug gem? or debug itself is leaky.

either way, debug should probably include big warnings so people don't load it in production...

**Comment by ko1** [comment]
Thank you for the information.

Retained 49809 ARRAY objects at: [/app/vendor/bundle/ruby/3.1.0/gems/debug-1.6.1/lib/debug/session.rb:1488](https://github.com/ruby/debug/blob/v1.6.1/lib/debug/session.rb#L1488)
-> added at thread creation. it should be free'ed when the thread is free'ed

And maybe all of them are based on same reason.

Maybe your program making many threads. I'll think about it.

**Comment by nilbus** [comment]
Nice discovery! I'll try to confirm this fix later today or sometime this week.
