### ISSUE TITLE
disabling/removing break points via browser devtools doesn't seem to work

### ISSUE THREAD

**Issue by kikonen** [ruby/debug#904]
**Your environment**

* `ruby -v`: 3.2.1
* `rdbg -v`: 1.7.1

**Describe the bug**

Breakpoint handling doesn't seem to work well with devtools integration. It seems that breakpoints can be added, but not disabled nor removed (i.e. they get disabled removed in browser devtools, but not in debug gem side in ruby process)

**To Reproduce**

**Expected behavior**

Have disable/enable of break points work

**Additional context**

In case it affects, running app inside docker container, and browser in localhost, rdbg port forwarded from docker container to localhost

**Comment by ono-max** [comment]
Thank you for reporting. 
Could you show us the sample program to reproduce this problem?

**Comment by kikonen** [comment]
Unfortunately that may not be possible, since cannot share  app where I was trying this out

**Comment by kikonen** [comment]
I may try sometime, but I already pretty much gave up trying with this "devtools" approach due to #902 (which made approach highly inpractical with docker container, which was having process constantly restarted with "rerun", more precisely multiple processes in different containers), and #901 and #904. Aka. I',m back using just plain CLI with remote debug.

**Comment by ono-max** [comment]
I think that https://github.com/ruby/debug/pull/948 fixes this problem. 

If you have any problem, please reopen or mention me. Thank you.
