### ISSUE TITLE
rdbg seems to not autoload .rdbgrc config file

### ISSUE THREAD

**Issue by awlamb** [ruby/debug#921]
**Your environment**

Ruby version: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin21]
rdbg version: rdbg 1.7.1

**Describe the bug**
.rdbgrc config file does not seem to be loaded automatically.

**To Reproduce**
```
> echo "config set skip_path /gems/" > .rdbgrc
> rdbg -c irb
(rdbg) config skip_path    # command
skip_path = nil                    # CONTROL: Skip showing/entering frames for given paths
(rdbg)
```
**Expected behavior**
Expected behavior should be that the skip_path contains the following:
```
skip_path = [/gems/]
```
**Additional context**
If i run `source .rdbgrc` in the rdbg console, i get the correct result:
```
(rdbg) source .rdbgrc    # command
(rdbg:/Users/alex.lamb/Code/rdbg-bug/.rdbgrc) config set skip_path /gems/
skip_path = [/gems/]               # CONTROL: Skip showing/entering frames for given paths
(rdbg) 
```

Additionally, this behavior also exists in a rails codebase when using `binding.break`

**Comment by ko1** [comment]
it is intentional: `./.rdbgrc` is not loaded (only loading `~/.rdbgrc`)

**Comment by awlamb** [comment]
Thank you!

**Comment by st0012** [comment]
@jgarber623 You can use the `-x` option to specify a custom configuration file. If the filename ends with `.rb`, it will be evaluated as Ruby script. Otherwise, it'd be evaluated as debugger commands (like `.rdbgrc` file).


```
$ be rdbg -x my_debug_script test.rb
(rdbg:my_debug_script) pp 'this is from a custom debug configuration'
"this is from a custom debug configuration"
[1, 6] in test.rb
=>   1| class Foo
     2|   def self.bar
     3|     binding.irb
     4|   end
     5| end
     6| binding.irb
=>#0    <main> at test.rb:1
(rdbg)
```

**Comment by jgarber623** [comment]
@st0012 Thank you! I’m so sorry, I overlooked this in the documentation.
