### ISSUE TITLE
`source': uninitialized constant 

### ISSUE THREAD

**Issue by CurtisHumphrey** [ruby/debug#992]
**Your environment**

* `ruby -v`: 3.1.2
* `rdbg -v`: fails

**Describe the bug**
when I run `rdbg -v` I get the following failure:
```
rdbg
/Users/curtis/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.7/lib/bundler/rubygems_ext.rb:18:in `source': uninitialized constant Gem::Source (NameError)

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList

... lot of from's
```

**Expected behavior**
The command to work

**Comment by ko1** [comment]
I have no idea about it.
Could you try re-install debug.gem?

**Comment by joe-sharp** [comment]
This was a Bundler issue: https://github.com/rubygems/rubygems/issues/5351
I think it is safe to close this, @CurtisHumphrey if you somehow are still experiencing this issue, run `bundle update --bundler`. You may need to `gem install bundler` ahead of time.
